### PR TITLE
BGE: Prevent multiple save clicks on entry form

### PR DESCRIPTION
**Pull request by psadie**
- Bug Fix: Fixed a bug that allowed users to make multiple unintended DI entries when spamming the save button

# Critical Changes

# Changes

- Save button will grey out and be disabled pending save.

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by psadie** [comment]
**lurch: attach W-031971

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008Lli3QAC" target="_blank">W-031971</a>

**Comment by melissabarber** [comment]
@psadie Is there a Github issue which will be resolved by this? If so, please add it under the Issues Fixed header similar to how this one is noted: https://github.com/SalesforceFoundation/Cumulus/pull/4124

**Comment by psadie** [comment]
> @psadie Is there a Github issue which will be resolved by this? If so, please add it under the Issues Fixed header similar to how this one is noted: #4124

Searched through and couldn't find a related issue we could close with this PR this time around

**Comment by melissabarber** [comment]
Release note not needed.

**Pull request merged**
