### PR TITLE
Rollups: allow a datetime for the date field

### PR DESCRIPTION
**Pull request by bethbrains**
# Critical Changes

# Changes
- Datetime is an acceptable data type for date field, allowing first/last operations by createddate, for instance.

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by randi274** [comment]
@force2b this looks good from UI, but can you verify the back-end change is ok too so we can merge this?

**Comment by force2b** [comment]
@randi274 Is this a critical one to get into the current release?

**Comment by force2b** [comment]
@bethbrains and @randi274 I'm not seeing where this works. In the example below I'm trying to populate a Date field on the Account with the CreatedDate for the Opportunity, however CreatedDate is not an available field.
image

**Comment by bethbrains** [comment]
@force2b the change was to allow datetime in the Date field to allow first/last sorting by a datetime like CreatedDate, not the Field To Roll Up. That would be a different story (that we can let the community ask for, as they did for this one).

**Pull request merged**
