### PR TITLE
Prevent Non-Skew Recurring Donation Batch Job Timeout

### PR DESCRIPTION
**Pull request by npsp-reedestockton**
# Critical Changes

# Changes
- We made a minor change to the non-skew recurring donation rollup job to help prevent timeout errors.

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by npsp-reedestockton** [comment]
@force2b ready for review

@sam-knox please take a quick look at the verbiage in changes section

**Comment by force2b** [comment]
@sam-knox Any thoughts on what the PR title should be?

**Comment by sam-knox** [comment]
@force2b - I think what Reede just put in works fine!

**Comment by npsp-reedestockton** [comment]
@force2b @sam-knox Made a suggested change to PR title.

**Comment by npsp-reedestockton** [comment]
@force2b Unit test to validate inner join not present for RD NonSkew Rollup complete.

**Comment by npsp-reedestockton** [comment]
**lurch: attach W-035135

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C93uQAC" target="_blank">W-035135</a>

**Comment by npsp-reedestockton** [comment]
Ready for testing @Julian88Tex

**Comment by Julian88Tex** [comment]
@npsp-reedestockton I've completed testing and approve this branch for merging. For some reason, I'm getting a message saying I'm not an authorized user for merging to master even though I've done this recently. Would you mind attempting to merge?

**Comment by Julian88Tex** [comment]
Testing completed and PR merged for W-035135

**Pull request merged**
