### PR TITLE
core logic for BDI support for Donation matching

### PR DESCRIPTION
**Pull request by davidhabib**
@njjc I've decided the BDI support for Opp/Pmt matching has reached a stable point and is ready for review.  Since I still need to do LDV testing, and UI work for the new options, I think we should start reviewing and merging the work into this new bdi-donations-REVIEWED branch, not dev.  I will also have Judi start some testing once I write up a beta document on the behavior.

# Critical Changes

# Changes
* The NPSP Data Importer now supports options for having Donations matched against existing Opportunities and Payments, rather than always creating new ones.  Please see <doc link here> for full details on this new feature set.

# Issues Closed

### CODE REVIEW

**Comment by judisohn** [comment]
@davidhabib Can't wait to play with it. :-)

**Comment by davidhabib** [comment]
@judisohn @jessingrass OK, I believe the BDI Donation matching is ready to be tested.  There is no UI yet, so you will have to set your options manually in custom settings.  Details in the quip doc I posted.  Note that if you run this from unmanaged code, when you click on the Start Data Import button, you will have to do the hack to fixup the URL by replace 'npsp.' with 'c.'

**Comment by davidhabib** [comment]
@njjc let's schedule an hour for me to walk you through this code.  is Monday OK?

**Comment by njjc** [comment]
@davidhabib sounds good, sent you an invite.

**Comment by davidhabib** [comment]
@njjc just finished checking in more tests.  coverage is now up to 95% for BDI_Donations, and 92% for BDI_DataImport_BATCH.

**Pull request merged**
