### PR TITLE
Updated comments. Added Conv top-level page. Found two unused variables.

### PR DESCRIPTION
**Pull request by kbromer**
Adds comments to properties, methods and classes.  Conv.htm to ApexDoc collection

### CODE REVIEW

**Comment by mrbelvedere** [comment]
Can an admin approve this request for build?

**Comment by kbromer** [comment]
**mrbelvedere: approved**

**Comment by mrbelvedere** [comment]
OK, build is started.  You can view status at http://ci.salesforcefoundation.org/job/Cumulus_feature_ext/64.  If you get a 404, please try again later as the build might be queued.  I will update the build status on the pull request when the build is done

**Comment by mrbelvedere** [comment]
**success**: The build succeeded!, view the build at http://ci.salesforcefoundation.org/job/Cumulus_feature_ext/64/

**Comment by mrbelvedere** [comment]
**success**: The build succeeded!, view the build at http://ci.salesforcefoundation.org/job/Cumulus_feature_ext/64/

**Pull request merged**
