### PR TITLE
Contributor docs edits for CCI2 and more

### PR DESCRIPTION
**Pull request by tet3**
# Critical Changes

# Changes
A pass at updating Contributor docs, primarily for CCI2, but with other edits as well.
- new _Coding Conventions_ page. This is based just on observations, and is marked as a work-in-progress
- much of CCI 1.x instruction preserved in new _Legacy CumulusCI_ page
- _Do the Work_ page updated to reflect new processes, link to _Contributing_ doc on main SFDO WP site
- git branching also added to _Do the Work_ page
- _Submit Your Feature_ updated for new PR template
- 'Starter' => 'Success' throughout
- copyright year and org in footer updated

# Issues Closed

### CODE REVIEW

**Comment by tet3** [comment]
@judisohn I was hoping this might be close enough to go ahead and publish for pre-Community Sprint reference, understanding that you want to have a more thorough look at all of this at some point.

**Comment by judisohn** [comment]
@tet3 THANK YOU!!!! @jlantz what do you think?

**Comment by njjc** [comment]
@tet3 WOW, I've got to hand it to you, this was a huge effort and you did an awesome job! THANK YOU!

**Comment by cdcarter** [comment]
this is the most exciting thing.

**Pull request merged**
