### PR TITLE
Add the Field API Name to the Template Fields.

### PR DESCRIPTION
**Pull request by kofijohnson**
# Critical Changes

# Changes
-Added field API names to be saved with Active_Fields__c and renamed label attribute for use in the Batch Template UI.
# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by randi274** [comment]
##lurch: attach W-026868

**Comment by kofijohnson** [comment]
You're right @randi274, we will remove the label when we implement the validation.

**Comment by kofijohnson** [comment]
**lurch: attach W-026868

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYCgGAAX" target="_blank">W-026868</a>

**Pull request merged**
