### PR TITLE
feature/1285-opp-add-amount

### PR DESCRIPTION
**Pull request by bermager**
Sorry, last one. I have to beat the robot -))

### CODE REVIEW

**Comment by mrbelvedere** [comment]
Your branch does not meet the feature branch naming requirements.  The name must use the format feature/NNN-description-of-feature where NNN is a valid GitHub issue number from the main repository.  Please rename your branch and submit a new pull request.

**Comment by ceiroa** [comment]
Hey @jlantz, do you see anything wrong with the branch naming? Why did mrbelvedere close it?

**Comment by ceiroa** [comment]
Hey @bermager, are you sure you have a git branch named as 1285/opp-add-amount? From what I see, it looks like you are trying to send the pull request directly from dev (which is the main trunk):

screen shot 2015-01-23 at 9 23 09 am

Try creating a branch with the name we discussed, apply the change in the branch, and then send the pull request from the branch.

**Comment by bermager** [comment]
aha, got it. Will try

**Pull request closed without merging**
