### PR TITLE
Final tweaks to ManageHouseholdUI for LockerService

### PR DESCRIPTION
**Pull request by davidhabib**
This pull request removes the warning from the ManageHouseholdUI page that LockerService is enabled.  It also removes three occurrences of preventDefault that we were needing in Winter '17 to prevent clicks on various dialogs from closing the window. 

# Critical Changes

# Changes
- The Manage Household page now runs fine with LockerService enabled.

# Issues Closed

### CODE REVIEW

**Comment by jlantz** [comment]
@dylanhansen and @jvarese can you review the release notes content?

**Comment by jlantz** [comment]
@jvarese ping

**Comment by jlantz** [comment]
@jvarese one more ping

**Comment by davidhabib** [comment]
hi @jjbennett It would be great if you could review this before next week when you are gone.  thanks.

**Pull request merged**
