### PR TITLE
Fix and consolidate namespacing

### PR DESCRIPTION
**Pull request by randi274**
# Critical Changes

# Changes
- Clean up namespacing usage to not rely upon npsp namespace
# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by randi274** [comment]
**lurch - attach W-030317

**Comment by lmeerkatz** [comment]
@davisagli Do you want to review before we call this ready?

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fQDQQA2" target="_blank">W-030317</a>

**Comment by lmeerkatz** [comment]
@davisagli Good catch! Since this isn't blocking, I've added fixing that reference to the acceptance criteria for another work item.

**Pull request merged**
