### PR TITLE
 Enhanced Recurring Donations - Work in Progress (Part 2)

### PR DESCRIPTION
**Pull request by force2b**
Includes the `deploy_rd2_config` cci task used to update the RecurringDonation object configuration in the target org after enabling Enhanced Recurring Donations [#4563]

# Critical Changes

# Changes

- The Recurring Donation Name will be auto-generated on the record creation when "Recurring Donations Settings" "Enable Automatic Naming"  field is checked. Automatic naming is disabled by default. [#4561]
   - The format for automatically named Recurring Donations is: `{!DonorName} {CurrencySymbol}{!Amount} - Recurring`. When naming is enabled for a multi-currency org, the name format is: `{!DonorName} {ISO Code} {!Amount} - Recurring`. 
   - Future releases will add the "Enable Automatic Naming" setting to the NPSP Settings page and will eventually support customizing the name format

# Issues Closed

# New Metadata

Apex Classes [#4573]:
- RD2_Donor
- RD2_Donor_TEST
- RD2_EnablementService
- RD2_EnablementService_TEST
- RD2_NamingService
- RD2_NamingService_TEST
- RD2_RecurringDonations_TDTM
- RD2_RecurringDonations_TEST
- TEST_OpportunityBuilder
- TEST_RecurringDonationBuilder
- TEST_SObjectGateway

Custom Label:
- RecurringDonationNameSuffix [#4561]

Custom Field:
- npe03__Recurring_Donations_Settings__c.EnableAutomaticNaming__c [#4561]

## Features Intended for Future Release (Should not be used at this point)

New Custom Fields
- npe03__Recurring_Donation__c.InstallmentFrequency__c
- npe03__Recurring_Donation__c.PaymentMethod__c
- npe03__Recurring_Donation__c.RecurringType__c
- npe03__Recurring_Donation__c.StartDate__c
- npe03__Recurring_Donation__c.Status__c

New Custom Object:
- RecurringDonationSchedule__c [#4665]

# Deleted Metadata

### CODE REVIEW

**Comment by Julian88Tex** [comment]
@davidmreed mind reviewing this PR since it has a change to the cumulus yaml?

**Comment by sam-knox** [comment]
@force2b - Customers can use Automatic Naming for current Recurring Donations, correct?

**Comment by Julian88Tex** [comment]
@sam-knox correct but only on create and not update. Enhanced Recurring Donations will allow for both create and update.

**Comment by force2b** [comment]
Technically true, however the option to enable automatic naming is not on by default and it has not been added to the NPSP Settings UI. The PR comment above noted it be added to NPSP Settings in a future release.

**Pull request merged**
