### PR TITLE
Imported Spanish translations

### PR DESCRIPTION
**Pull request by dospromptman**
Imported from file `Bilingual_es_2016-04-14 0147.stf` with the exception
of the following translation keys:

- `CustomField.Goal.OrigGoalId.FieldLabel`
- `CustomField.Metric.OrigMetricId.FieldLabel`
- `LayoutSection.DataImport__c.Data Import Layout.Account1 Information_3` :dancer: 
- `LayoutSection.DataImport__c.Data Import Layout.Account2 Information_5` :dancer: 
- `LayoutSection.DataImport__c.Data Import Layout.Campaign Information_8` :dancer: 
- `LayoutSection.DataImport__c.Data Import Layout.Contact2 Information_4` :dancer: 
- `LayoutSection.DataImport__c.Data Import Layout.Custom Links_9` :dancer: 
- `LayoutSection.DataImport__c.Data Import Layout.Donation Information_7` :dancer: 
- `LayoutSection.DataImport__c.Data Import Layout.Home Address_6` :dancer: 
- `LayoutSection.Metric.Formato de medición de finalización.Descripción_1`
- `LayoutSection.Opportunity.Opportunity Layout.Vínculos personalizados_5`
- `LayoutSection.WorkCoaching.Coaching Layout.Coaching Information_0`
- `PicklistValue.Standard.opportunityStage.Cerrada perdida`
- `PicklistValue.Standard.opportunityStage.Comprometida`
- `PicklistValue.Standard.opportunityStage.Pledged`
- `PicklistValue.Standard.socialPostClassification.Customer Case`
- `PicklistValue.Standard.socialPostClassification.Inquiry`
- `PicklistValue.Standard.socialPostClassification.Lead`
- `PicklistValue.Standard.socialPostClassification.Outreach`
- `PicklistValue.Standard.socialPostClassification.Product Review`
- `PicklistValue.Standard.socialPostEngagementLevel.Commented`
- `PicklistValue.Standard.socialPostEngagementLevel.Resolved`
- `PicklistValue.Standard.socialPostEngagementLevel.Reviewed`
- `PicklistValue.Standard.socialPostEngagementLevel.Submitted`
- `QuickAction.New_Household_Account` :dancer: 
- `QuickAction.New_Organization` :dancer: 
- `RecordType.Opportunity.Grant`
- `RecordType.Opportunity.Matching_Donation`
- `RecordType.Opportunity.Membership`

These translations were not imported because they did not match objects in my fresh dev org.  Some are likely due to translations being included in the import file that were specific to custom modifications made in the org in which the translations were exported.  Others are likely due to having a different feature set enabled between the translation org and my dev org.

Many of these keys do not have translations associated with them, and exist in the translation import file in the 'UNTRANSLATED' section.

The keys that were not imported but _did_ have a corresponding translation in the import file are marked with a :dancer: above.

# Contribution Info

These translations were contributed and reviewed by a group of volunteer translators, including Laura Diaz, Elena Inurrategui, Rosario Gonzalez Moron, Raúl González García, Mariana Mazzeo, and María Florencia Salvador . ¡Gracias a todos!

# Critical Changes

# Changes

Spanish translations have been added.

# Fixes
[Issue 1679](https://github.com/SalesforceFoundation/Cumulus/issues/1679)

### CODE REVIEW

**Comment by dospromptman** [comment]
@mpusto Can you review the list of keys that were not imported?  Let me know if omitting any of these translations should be a blocker for merging this PR.

Also, could you please update the PR description to give more accurate attribution in the 'Contribution Info' section?

**Comment by dospromptman** [comment]
@jlantz I've never worked with translations, nor translation metadata before.  Can you look this over and let me know if you think there might be any issues in this metadata that would cause issues when packaging and pushing the update out to orgs?

Will they need any features turned on in their org to be able to receive this update?  What if they deleted a picklist value, but the translation metadata refers to that value? Etc.

**Comment by mpusto** [comment]
I've reviewed them and I don't think they should block us from getting the translation in. When do you need a final answer by? I can check with the translation group.

**Comment by dospromptman** [comment]
@mpusto This PR can remain here indefinitely, until we decide to merge it

**Comment by dospromptman** [comment]
@jlantz It looks like Bamboo answered my concerns about deploying these translations to an org...

```
14-Apr-2016 13:39:50	*********** DEPLOYMENT FAILED ***********
14-Apr-2016 13:39:50	Request ID: 0Af3600000SXDWwCAP
14-Apr-2016 13:39:50	
14-Apr-2016 13:39:50	All Component Failures:
14-Apr-2016 13:39:50	1.  translations/es.translation -- Error: Not available for deploy for this organization
14-Apr-2016 13:39:50	
14-Apr-2016 13:39:50	*********** DEPLOYMENT FAILED ***********
```

Is it just not possible to distribute these translations in the NPSP package?

**Comment by mpusto** [comment]
It's possible, I know @davidhabib has done it with Volunteers in the past. I think there is just a certain way to do it. @jlantz will know more.

**Comment by davidhabib** [comment]
@jlantz @dospromptman I suspect that Translation Workbench needs to be enabled in the org the build system is trying to deploy to.  @jlantz can you fix this so all of our build orgs have translation workbench enabled?  do you need dev to do anything?

**Pull request closed without merging**
