### PR TITLE
W-022118 TDTM exclude username case bug [deprecated]

### PR DESCRIPTION
**Pull request by Julian88Tex**
# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by Julian88Tex** [comment]
@force2b @Safiyab hm it appears that @salesforce-org-metaci did a merge into my branch and somehow that became part of my commit... attempt to undo that commit but having issues

**Comment by force2b** [comment]
@Julian88Tex yeah that is odd. What do you think @davidmreed?

**Comment by Julian88Tex** [comment]
Created https://github.com/SalesforceFoundation/Cumulus/pull/4547 to replace this PR and will be closing this one.

**Comment by davidmreed** [comment]
I don't see the problematic commit. What was the issue with Mr. Belvedere?

**Comment by Julian88Tex** [comment]
@davidmreed so this is the problematic one https://github.com/SalesforceFoundation/Cumulus/pull/4527/commits/ae8016f9994b9155e337dcf2efe795384ed02c49

I'm pretty sure part of it was an oversight on my end. There was a an automatic merge down from master but somehow locally it was added to my commit. I think it was an order of operations issue that I'm guessing was something like this:

1. automatic merge from master to my branch to keep things up to date
2. me pulling those changes in locally
3. rollback on master done by someone for some reason
4. me not noticing rollback and adding previously merged changes to my commit

I'm not a git expert so not entirely sure this is possible or logical but this is as close as I've been able to get.

**Pull request closed without merging**
