### PR TITLE
Enhanced Recurring Donations pilot telemetry

### PR DESCRIPTION
**Pull request by davidmreed**
Added telemetry to determine whether Enhanced Recurring Donations is enabled.
# Critical Changes

# Changes

- We added Feature Telemetry for upcoming Recurring Donation enhancements. No data should be collected until this functionality is released at a later date. NPSP Feature Telemetry collects feature and usage metrics when customers use our products. We use this information to understand the level of usage and adoption of various NPSP features. No personally identifiable information is collected through NPSP Feature Telemetry. Read more about NPSP Telemetry here: https://powerofus.force.com/s/article/NPSP-Feature-Telemetry. 

# Issues Closed

# New Metadata
Feature Parameters:  

- IsEnabled_RecurringDonations2.featureParameterBoolean

# Deleted Metadata

### CODE REVIEW

**Comment by npsp-reedestockton** [comment]
**lurch: attach W-035303

**Comment by npsp-reedestockton** [comment]
@sam-knox we needed to re-create this PR due to a merge error.  Don't actually believe anything needs to be done by you, but adding you as a reviewer in case you want to double check.

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C9P9QAK" target="_blank">W-035303</a>

**Comment by Julian88Tex** [comment]
WI has been closed: https://foundation.lightning.force.com/lightning/r/agf__ADM_Work__c/a2x1E000001C9P9QAK/view

**Pull request merged**
