### PR TITLE
Feature/1285 opp add amount

### LINKED ISSUE #1285: As a user, changing an opportunity from a null amount to a positive amount should create a payment.
[Per this hub thread.](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D58000001nHu3r&fromEmail=1)
[Change here.](https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/PMT_PaymentCreator.cls#L243)

### PR DESCRIPTION
**Pull request by bermager**
please work -)

# Warning

# Info

# Issues
Fixes #1285.

### CODE REVIEW

**Comment by mrbelvedere** [comment]
Can an admin approve this request for build?

**Comment by bermager** [comment]
alright. now I get how it works. Thanks, Ceiroa.

**Comment by ceiroa** [comment]
**mrbelvedere: approved**

**Comment by mrbelvedere** [comment]
OK, build is started.  You can view status at http://ci.salesforcefoundation.org/job/Cumulus_feature_ext/65.  If you get a 404, please try again later as the build might be queued.  I will update the build status on the pull request when the build is done

**Comment by mrbelvedere** [comment]
**success**: The build succeeded!, view the build at http://ci.salesforcefoundation.org/job/Cumulus_feature_ext/65/

**Comment by mrbelvedere** [comment]
**success**: The build succeeded!, view the build at http://ci.salesforcefoundation.org/job/Cumulus_feature_ext/65/

**Pull request merged**
