### PR TITLE
Multi-Currency Support for UDRs

### PR DESCRIPTION
**Pull request by jamesmelville**
Allow UDRs to detect if they are aggregating a currency and if so
convert that value correctly. Added test which exercises the routine if
tested in a multicurrency environment

### CODE REVIEW

**Comment by judisohn** [comment]
Thanks for the contribution @jamesmelville - We are in the process of reworking the engine behind rollups, so I'm not sure how this might fit. We'll be in touch once someone has a chance to review. Thanks again!

**Comment by jamesmelville** [comment]
Thanks @judisohn, glad to hear there's an update coming. I was also thinking about putting in a pull request which would trigger rollup recalculations if the currency was changed on the Contact / Account / Household. Is there any point in doing that before you complete this refactoring?

**Comment by judisohn** [comment]
@jamesmelville Honestly, no -what's coming is a rather large departure from the current engine. Probably best to wait and see and then raise to our attention and close any gaps as you see them.

**Comment by force2b** [comment]
@jamesmelville Out of curiosity, was there an existing open issue in github for this?

**Comment by jamesmelville** [comment]
@force2b I hadn't actually logged a github defect, but I did post the issues I was looking at here: https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CtL2&fId=0D58000003bMns3

I'm interested in fixing
1. This issue in this PR - where multi currency UDRs are wrong
2. The gap in functionality mentioned to Judi above, where totals aren't recalculated when currency is changed.

**Comment by force2b** [comment]
Closing because it has been merged into a different PR

**Pull request closed without merging**
