### PR TITLE
Feature/jbury autocomplete as module

### PR DESCRIPTION
**Pull request by jjbennett**
# Critical Changes

# Changes

# Issues Closed

### CODE REVIEW

**Comment by jjbennett** [comment]
@njjc - this is the pull request that is switching the autocomplete over to the shared component.

**Comment by njjc** [comment]
@dospromptman I'm still unable to get a diff here. I checked out this branch in git and did

```
git fetch lightningcomponents
git diff HEAD...lightningcomponents/autocomplete/master

fatal: ambiguous argument 'HEAD...lightningcomponents/autocomplete/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

So I then did
```
git diff HEAD...lightningcomponents/autocomplete
```
and the result was blank. Any ideas? Are there just no changes for this merge?

**Comment by jjbennett** [comment]
@njjc there were definitely changes - https://github.com/SalesforceFoundation/Cumulus/pull/2444/commits/f17c733df96fedce690228cfce3d44cef88e0ae9 (changes are on the left)

**Comment by njjc** [comment]
I'm sure that's the case, I just can't figure out how to see them in a diff, which I need to do before I can merge.

**Comment by dospromptman** [comment]
I can't detect a difference, either.  I'll need to investigate a bit more to see exactly what happened here, but as a quick test I did a comparison of the actual files in each branch using the diff tool (not the git diff tool).  This indicated no differences between the actual files of each branch:

```zsh
$ cd /tmp
$ git clone git@github.com:SalesforceFoundation/Cumulus.git Cumulus_dev
Cloning into 'Cumulus_dev'...
remote: Counting objects: 47962, done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 47962 (delta 19), reused 0 (delta 0), pack-reused 47915
Receiving objects: 100% (47962/47962), 64.92 MiB | 962.00 KiB/s, done.
Resolving deltas: 100% (37407/37407), done.
Checking connectivity... done.
$ cp -r Cumulus_dev Cumulus_autocomplete
$ cd Cumulus_autocomplete
$ git checkout feature/jbury-autocomplete-as-module
Branch feature/jbury-autocomplete-as-module set up to track remote branch feature/jbury-autocomplete-as-module from origin.
Switched to a new branch 'feature/jbury-autocomplete-as-module'
$ cd ..
$ diff --recursive --brief Cumulus_dev/ Cumulus_autocomplete/
Files Cumulus_dev/.git/HEAD and Cumulus_autocomplete/.git/HEAD differ
Files Cumulus_dev/.git/config and Cumulus_autocomplete/.git/config differ
Files Cumulus_dev/.git/index and Cumulus_autocomplete/.git/index differ
Files Cumulus_dev/.git/logs/HEAD and Cumulus_autocomplete/.git/logs/HEAD differ
Only in Cumulus_autocomplete/.git/logs/refs/heads: feature
Only in Cumulus_autocomplete/.git/refs/heads: feature
```

I looked at the f17c733 commit that Jenny pointed out, but if you compare, for example, the [autocomplete.cmp file currently in dev](https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/aura/autocomplete/autocomplete.cmp), it has all of the changes from that commit.

Somehow, somewhere, this branch already got merged, I think.  Like I said, I'll have to do some more digging to figure out how and when that happened.

**Comment by njjc** [comment]
Using blame it looks like you merged in those changes 8 months ago. Weird.

**Pull request closed without merging**
