### PR TITLE
[HOLD] Support Payment Allocations in Customizable Rollups Engine

### PR DESCRIPTION
**Pull request by njjc**
# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by njjc** [comment]
@force2b this is good to go for review; I'll submit the UI work in a separate pull request.

**Comment by njjc** [comment]
@force2b don't merge this yet, please.

**Comment by force2b** [comment]
@njjc This PR is closed now?

**Comment by lparrott** [comment]
@force2b @njjc My fault, I deleted the branch that this was originally being merged into, this should not be closed.

**Comment by njjc** [comment]
I'll reopen this when the UI is ready.

**Comment by force2b** [comment]
Sounds good. I'll hold code review until the final PR is ready.

**Pull request closed without merging**
