### PR TITLE
Increase the maximum polling time for rollup deployments to 90 seconds

### LINKED ISSUE #3346: Increase Customizable Rollups' Deployment Timeout to 3 Minutes
Users may receive timeout error messages while creating or deleting Filter Groups, even though the Custom Metadata Type records eventually deploy. After hitting the Create or Delete button, the deployment is shown as in progress in Setup --> Deployment Status. When it does finish (after a few minutes), it shows as succeeded. However, the LEX page displays the following error to the user via a toast at the top of the page: 

Saving the Filter Group has timed out. Please see the Customizable Rollups documentation for more information.

Screenshot of initial "saving..." message:
filter group 1

Screenshot of false error:
filter group 2

### PR DESCRIPTION
**Pull request by kofijohnson**
# Critical Changes

# Changes

# Issues Closed
Fix #3346

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by kofijohnson** [comment]
@randi274 could you test again the "Deployment Failure" use case. You should be able to get now the failure message right away.

**Comment by randi274** [comment]
@kofijohnson I'm still seeing this time wait to time out after the full 3 minutes, though the deployment fails after 90 seconds. Maybe we can review this when you get in, or go with the easier fix from commit c756062 and just shorten the polling time to 90 seconds?

**Comment by randi274** [comment]
@jesslopez-sf as a heads up, we're changing this to 90 seconds, since that's when the deployment is timing out anyways. Let us know if you have any concerns with that change.

**Comment by jesslopez-sf** [comment]
@randi274 No concerns with that change. Thanks for the heads up!

**Pull request merged**
