### PR TITLE
As a user, I'd like to have Acknowledgment Status fields on Opportunity and Payment

### PR DESCRIPTION
**Pull request by mrbelvedere**
Community contribution submitted by @judisohn

This was brought up at the NPSP Community Sprint as needed. It's a picklist to track the acknowledgment status (including Do Not Acknowledge) and a date field to track when a donation (or payment) was acknowledged. It's something that we end up creating as custom fields on nearly every project.

# Critical Changes

# Changes

These fields should be added to Opportunity page layouts and can be worked in to acknowledgment merge processes.

# Issues

### CODE REVIEW

**Comment by njjc** [comment]
This is awesome! You are the best, @judisohn!

**Comment by judisohn** [comment]
@jlantz deserves the credit for making a very intimidating process so click-easy!

**Comment by njjc** [comment]
It takes a lot of code and a special kind of coder to enable "clicks, not code"! I feel lucky every day to work with Jason :+1:

**Comment by davidhabib** [comment]
@jlantz It looks like this did not kick off the automated build.

**Comment by davidhabib** [comment]
@jlantz This still hasn't built.

**Comment by jlantz** [comment]
I'm working on implementing the build process into the contributor tool either today or tomorrow.  Once the build process is in place, we'll use it to review this pull request and merge for the next release.

**Comment by njjc** [comment]
Cleaned up and moved his pull request [here](https://github.com/SalesforceFoundation/Cumulus/pull/1483).

**Pull request closed without merging**
