### PR TITLE
Update NPSP Settings to include Matched Donor in top header

### PR DESCRIPTION
**Pull request by jjbennett**
# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by jjbennett** [comment]
@sam-knox - this is the item we spoke about in the standup today that will require screen shot updates.

**Comment by sam-knox** [comment]
@jjbennett - Jenny, what branch can I use in a scratch org to see the new settings page?

**Comment by force2b** [comment]
@sam-knox You can use this branch to see that - `feature/jen-settings-roles`

**Comment by sam-knox** [comment]
@force2b - Thanks Mike. Still learning how to navigate these PR/branch thingys.

**Pull request merged**
