### PR TITLE
CCI: New task for Deploy_Dev_Nima to reset overrides on the BGE_Template object

### PR DESCRIPTION
**Pull request by force2b**
Create a new CCI task (`deploy_dev_nima`) that applies the New and Edit overrides on the BGE_Template custom object to point to the BGE_TemplateCreation component.

# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by randi274** [comment]
@force2b is this build error something we need to be concerned about?

**Comment by force2b** [comment]
No. I renamed the branch to make it a child of bge. Looks like that build failure is because it was looking for the old branch name.

**Comment by force2b** [comment]
The namespaced build on the new branch name passed. The other build is almost done.

**Comment by davisagli** [comment]
@force2b note that the code which finds child branches is case sensitive, so this branch would need to be named `feature/BGE__cci-new-nimacloud-task-for-overrides` instead of `feature/bge__cci-new-nimacloud-task-for-overrides` in order to be recognized as a child of `feature/BGE`.

**Comment by force2b** [comment]
@davisagli Thanks. I can fix that, though ideally we'll merge into feature/bge before we have to worry about a sync into the child from bge.

**Pull request merged**
