### PR TITLE
Feature/1368 duplicate

### LINKED ISSUE #1368: As a developer, I've set up packaged matching rules for NPSP.
https://help.salesforce.com/apex/HTViewHelpDoc?id=matching_rules_create.htm&language=th

### PR DESCRIPTION
**Pull request by njjc**
# Warning
# Info
This release includes packaged NPSP Contact Matching Rules; to take advantage of these rules, create Duplicate Rules that use them.
# Issues
Fixes #1368

### CODE REVIEW

**Comment by njjc** [comment]
@jlantz we'd like to hold up the build for these matching rules, as we've had a lot of requests and I have the blog post on the hopper. Can you take a look at the new metadata type and the associated build problems before cutting the release? Thanks!

**Comment by jlantz** [comment]
I should have this resolved this morning.  The MatchingRule metadata type
follows a different pattern that other metadata files for how you name it
in the package.xml that I'm trying to get in place in CumulusCI.

**Comment by jlantz** [comment]
The build issues should be resolved now.  I had to modify CumulusCI to handle the unique pattern of matching rules.  I've run two builds.  The first to test deploying the matching rules, the second to test the deletion script to make sure it correctly deletes the matching rules.

Note that this pull request upgrades our package to API 33 since 33 is required to include matching rules.  All tests pass and we get no deployment issues.  My vote would be to go ahead and merge it but I'd like to get the opinions of others on the team first.

**Comment by njjc** [comment]
I agree, let's discuss during standup.

**Pull request merged**
