### PR TITLE
As a developer, I'd like to programmatically initiate household account renaming through apex

### LINKED ISSUE #846: As an admin, I would like to be able to visually see that a batch job failed when looking at the Job Progress widget
The widget only shows you if the job successfully completes. It does show you anything (the progress bar is blank) if the job finished but was not successful.

### LINKED ISSUE #864: As a developer, I'd like to programmatically initiate household account renaming through apex
If using a custom naming format, such as "{{!FirstName} {!Middle_Initial__c} {!LastName}", the standard trigger on the Contact object will not flag a change to the Middle_Initial__c as a reason to re-evaluate the household naming. A custom trigger, however could detect that change and make a call to the NPSP class to handle the naming updates.

### PR DESCRIPTION
**Pull request by mrbelvedere**
I chose to name the class HH_HouseholdNaming_Action instead of HH_HouseholdNaming_API to stay consistent with Salesforce action naming conventions but I am not tied to that.

Once again, labels got all weird via the contrib tool, so only my changes to HH_HouseholdNaming_Action and HH_HouseholdNaming_TEST should be merged.

The test class is getting repetitive, and if you don't want to merge the tests as is, I would understand that. The class is just a minor wrapper around the tested code, so the test method provided is purely for coverage reasons.

# Contribution Info

This external contribution was submitted by @cdcarter and Fixes #864 

# Critical Changes

# Changes

Adds a global @InvocableMethod class HH_HouseholdNaming_Action to provide a method to force household renaming programmatically (via Apex, Flow, or PB). 

# Issues

### CODE REVIEW

**Comment by cdcarter** [comment]
Welllp. This is actually for #864 - so this PR name is way off (and so is my contribution record). Any to fix that, @jlantz?

This PR closes #864 - as a developer I'd like to programmatically fire HH naming via Apex

**Comment by njjc** [comment]
Awesome, thanks for this @cdcarter! I'm interested in eventually having a whole library of actions, so I like your _Action notation. I'll discuss with the team tomorrow.

**Comment by cdcarter** [comment]
Thanks for the rename! 

I think adding InvocableMethods is a great step toward a more API based NPSP though the way they live in the namespace is a bit annoying.

If you/core team come up with a list of functions that you want invocable-ized, that'd be a great thing to make public for the community to work through!

**Comment by cdcarter** [comment]
replaced with pr #1883

**Pull request closed without merging**
