### PR TITLE
Fix styling on Batch Settings page

### PR DESCRIPTION
**Pull request by patrick-yan-sf**
Don't merge before Jan. 10

# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by patrick-yan-sf** [comment]
**lurch: Attach W-030222

**Comment by patrick-yan-sf** [comment]
@jjbennett This is ready for review

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fQ5RQAU" target="_blank">W-030222</a>

**Comment by patrick-yan-sf** [comment]
@rponti-sforg This is ready for testing

**Comment by patrick-yan-sf** [comment]
@sam-knox - Do we need to add release notes for this PR?  
It is not really a bug - more of a formatting change.

**Comment by sam-knox** [comment]
@patrick-yan-sf - As long as it's just fixing something that's broken and not changing how the settings page is supposed to render, then no.

**Pull request merged**
