### PR TITLE
Changed text value for stgHelpAutoAffil

### PR DESCRIPTION
**Pull request by sam-knox**
# Critical Changes

# Changes

We changed the on-screen help text for the Automatic Affiliation Management setting (in NPSP Settings). This should clarify how this setting works with regard to Account record types.

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by sam-knox** [comment]
**lurch: attach W-033675

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087vVCQAY" target="_blank">W-033675</a>

**Comment by sam-knox** [comment]
@rponti-sforg - Not sure if there's much to QA here, but if so, it's ready.

**Comment by rponti-sforg** [comment]
Testing for this PR is complete.  Tests have passed.

For further testing details, see: https://foundation.lightning.force.com/lightning/r/agf__ADM_Work__c/a2x1E0000087vVCQAY/view

Merging PR and deleting branch.

**Pull request merged**
