### PR TITLE
Improvements for Manage HH UI

### PR DESCRIPTION
**Pull request by dextermilo**
* Wrap javascript in IIFE, add 'use strict'
* Improved the formatting of the javascript, I suggest viewing diff with ?w=1
* Fix for address block help displaying incorrectly when no address has yet been entered
* Add save/delete/cancel buttons to top of UI
* Prevent Save status message from pushing UI and moving buttons 

Refs #1385

### CODE REVIEW

**Comment by kbromer** [comment]
:+1:

**Comment by kbromer** [comment]
Thank you @dextermilo for taking care of this

**Comment by dextermilo** [comment]
@kbromer here you go, let me know if this works

**Comment by dextermilo** [comment]
Ah, you replied already ;)

**Comment by kbromer** [comment]
:ear:

**Comment by kbromer** [comment]
@njjc can you take a look at this pull from Ryan - run the build on it, and we can merge it for next release?  Thx!

**Comment by kbromer** [comment]
@njjc hold on this for now

**Comment by davidhabib** [comment]
@kbromer given the reimplementation of Manage Household UI, I think we can close this pull request.  agreed?

**Comment by kbromer** [comment]
Yes, agreed

**Pull request closed without merging**
