### PR TITLE
Detect Rich Text fields using Describe Info

### PR DESCRIPTION
**Pull request by bdvorachek**
# Critical Changes

# Changes
- Updated the form field component to retrieve field metadata in order to detect when a field being rendered is a rich text field.
# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by bdvorachek** [comment]
**lurch: attach W-38063

**Comment by bdvorachek** [comment]
**lurch: attach W-038063

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HphDQAS" target="_blank">W-038063</a>

**Comment by annejackson** [comment]
Merging this into gift-entry feature branch since it's been Dev reviewed/approved.

**Pull request merged**
