### PR TITLE
Payment Allocations Unit Tests, and Fixes for 2 Way Sync

### PR DESCRIPTION
**Pull request by jbrandolinisf**
# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by jbrandolinisf** [comment]
Hi @ptewson-sfdo,

I somehow committed these to the other branch, so I am calling them out explicitly for review: 

These tests in ALLO_PaymentSync_TEST should be reviewed:

- validateUpdatingPmtAllocUpdatesOppAllocs
- validateNullAndZeroAmountsForPayments
- validateNullAndZeroAmountsForOpps
- validateNegativePaymentAmounts

Thanks!

John

**Comment by weizsforg** [comment]
Hi @jbrandolinisf , looks like there are some conflicts in this PR.

**Comment by jbrandolinisf** [comment]
Hi @weizsforg,

I somehow committed these to the other branch, so I am calling them out explicitly for review:

These tests in ALLO_PaymentSync_TEST should be reviewed:

validateUpdatingPmtAllocUpdatesOppAllocs
validateNullAndZeroAmountsForPayments
validateNullAndZeroAmountsForOpps
validateNegativePaymentAmounts
Thanks!

John

**Comment by weizsforg** [comment]
Great job @jbrandolinisf ! 

Those four unit test cases looks good! 

Looks like somehow system merged a lot of extra stuff into this PR. I didn't review other files except the 4 unit test cases. It is good to remove unnecessary files so we don't accidentally change something when merge to another branch.

Also, there are other issues W-032026, W-032028, W-032360, W-032361, W-032362 also ready for review. Do we have the unit test to cover those WIs?

**Comment by jbrandolinisf** [comment]
@weizsforg  - They were fixed under this PR, and covered either by existing unit tests, or exposed as issues by these.  You should look at any changes to ALLO_PaymentSync_SVC.cls, as I had to make a fix here for three of the issues (including #7, which we talked about via chatter).

**Comment by weizsforg** [comment]
Thanks for the reply @jbrandolinisf! 
I have reviewed the changes to ALLO_PaymentSync_SVC class. And did a smoke test about the bugs we found. All looks good! 
Do we need someone from NPSP to do a quick check or pass for QA? what is the next step of this PR?

**Comment by ptewson-sfdo** [comment]
Thanks @weizsforg! I'm satisfied with your review and I've had a chance to look it over as a high level. I'm happy merging this into the parent branch with your approval, since we will be doing follow-on dedicated QA for this entire work stream before it hits master. Thanks!

**Comment by weizsforg** [comment]
That is awesome @ptewson-sfdo ! 
I just approved the PR. Looks like we need to fix the conflict before merge it @jbrandolinisf . 
Please let me know if you guys need me later! Thanks!

**Pull request merged**
