### PR TITLE
BUG/#1285 As a user, changing an opportunity from a null amount to a positive amount should create a payment

### PR DESCRIPTION
**Pull request by bermager**
Hello.

### CODE REVIEW

**Comment by mrbelvedere** [comment]
Your branch does not meet the feature branch naming requirements.  The name must use the format feature/NNN-description-of-feature where NNN is a valid GitHub issue number from the main repository.  Please rename your branch and submit a new pull request.

**Comment by ceiroa** [comment]
Hi @bermager. Thanks for contributing to our repo! As you saw, our robot posted regarding the naming convention to follow. This is just so it can be automatically picked up and run against our test org. Once that happens, you'll see your branch being build at http://ci.salesforcefoundation.org/. Let me know if you have any questions.

**Comment by bermager** [comment]
Aha, now I got it -))
Thanks, but still didn't understood how should I name it :D tried 5 times -))

**Comment by bermager** [comment]
So I don't need to recreate pull request anymore? You got the changes now?

**Comment by ceiroa** [comment]
There were a lot of emails coming through, so I got a little lost... I think maybe you are missing the "feature/" part at the beginning. For example:

feature/1285-add-opp-amount

**Comment by bermager** [comment]
Ok, sorry for creating so many requests, first time is always first time -))

**Comment by ceiroa** [comment]
No problem. But I don't think we got the final pull request yet. If we did it'd be listed under https://github.com/SalesforceFoundation/Cumulus/pulls

**Comment by bermager** [comment]
well, I tried another one. "feature/1285-opp-add-amount" didn't worked either.

**Pull request closed without merging**
