### PR TITLE
Removing Payment Allocations settings from Allocations settings page

### PR DESCRIPTION
**Pull request by njjc**
# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by njjc** [comment]
I just reverted to the commit before the payment allocations PR was merged. It looks the same after this PR as it does in managed NPSP today. 

A small concern is related to packaging: do we need to add references to the labels that are removed from this page for packaging reasons? @davisagli

**Comment by annejackson** [comment]
**lurch:attach W-030157

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fQ0CQAU" target="_blank">W-030157</a>

**Comment by force2b** [comment]
Something is not right with this page. The lookup icon on the Default Allocation field is missing again. 
image

**Comment by njjc** [comment]
Nice catch @force2b !

**Comment by davisagli** [comment]
@njjc I'm not quite sure how the packaging org will behave with regard to the removed labels but I suspect that they will still be included in the package due to being referenced explicitly in CustomLabels.labels. Does that sound right @cdcarter @force2b?

**Comment by annejackson** [comment]
All looks good- merging PR. @force2b @dvenor @davisagli  fyi.

**Pull request merged**
