### PR TITLE
Display Contact Portal Info on Merge Selection Page

### LINKED ISSUE #3338: NPSP Contact Merge Should Respect Portal User Status
The NPSP Contact Merge utility allows you to merge Contacts regardless of whether or not they are Partner or Customer Portal (Communities) Users. Because we aren't displaying portal status on the field set for each Contact on the merge screen, you can easily select a Master that is not a portal user and ultimately lose portal access after the merge. Ideally, we can display portal status and also prevent the non-portal status as master.

The native (non-NPSP) Classic version of Contact Merge prevents this from happening. Here are screenshots and Steps to Repeat for the more desired outcome:

**Step 1:** Merge Contacts
step 1

**Step 2:** Select Contacts to Merge. Note the columns showing Customer and Partner Portal "status".
step 2

**Step 3:** On screen showing field values for each Contact, note the Portal User option. In this Case, the Partner Portal Contact is selected as Master, but the "Not a Portal User" option is selected in the Portal User column. 
step 3

**Step 4:** This scenario results in an error.
step 4

**Super Condensed Steps to Repeat**
1. Set up and activate a Community in your scratch org. Add Partner Community User and Partner Community Login User Profiles as Members of the Community. (If you want a demo of setting up a Community, let me know).
2. Create a Contact named Jack Black. The Black Household is automatically created.
3. Add a Contact called Jackie Black to the Black Household.
4. Edit the Contact Page Layout so that you have the Enable Partner User and Disable Partner User buttons in the Custom Buttons section (for Classic) and the Actions versions of these in the Salesforce Mobile and Lightning Experience Actions section.
5. Go to the Black Household Account page. Click the button to Enable as Partner.
6. Go to Jack Black's Contact page. Click the button to Enable Partner User. This takes you to a User screen with his info filled out. Choose the Partner Community Login role/profile.
7. First try merging using the classic non-NPSP Contact Merge to merge Jack and Jackie Black. Your actions will mirror the screenshots above and you won't be able to merge.
8. Then go to the NPSP Contact Merge tab. Try to merge Jack and Jackie Black and you can. Selecting Jackie as master will remove the new merged Contact as a Partner User.

### PR DESCRIPTION
**Pull request by jjbennett**
# Critical Changes

# Changes
- NPSP Contact Merge now displays which Contacts are Portal Users (Customer Community, Partner Community, etc.).
- NPSP Contact Merge now displays the Contact Id.
- An additional merge button has been added to the bottom of NPSP Contact Merge so you don't have to scroll back to the top of the page to initiate a merge process.

# Issues Closed
Fixes #3338 

Ideas
Idea [1348](https://powerofus.force.com/hub-ideas/1348) - Contact IDs on Merge Page
Idea [1294](https://powerofus.force.com/hub-ideas/1294) - Additional Merge Button at Bottom of Merge Contacts Screen

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by jjbennett** [comment]
@joy-sfdo - please wait to merge until the merge freeze has been lifted for the next sprint. Thanks!

**Comment by rponti-sforg** [comment]
@joy-sfdo Hi Joy - Can you mark this ticket as "reviewed" so I can merge it and then delete the branch?  We have until 8pm PST, 7/17 until NGO Merge Freeze.  Thank you.  Rick

**Comment by sam-knox** [comment]
@joy-sfdo - If you could take a look at the Changes section too I would appreciate it. I want to make sure I've captured everything this PR includes. Thanks!

**Comment by rponti-sforg** [comment]
QE testing has been completed and corresponding tickets updated.  Ready for merge.

**Comment by rponti-sforg** [comment]
@alex-peralta @jjbennett Hi Alex ... It appears I don't have "write access" to the Cumulus repo.  I don't see a Merge button for this PR.  Trying to merge this branch before NGO Merge Freeze.  Thanks!

**Comment by annejackson** [comment]
Merging for @rponti-sforg

**Comment by rponti-sforg** [comment]
Due to lack of repo permissions and approaching NGO merge freeze deadline, Anne Jackson will be merging this branch and deleting it for me.

**Comment by annejackson** [comment]
Merged and now deleting. :)

**Pull request merged**
