### PR TITLE
Orphaned Payment Allocation bug

### PR DESCRIPTION
**Pull request by KietTruongSFDO**
# Critical Changes

# Changes
* We have fixed a bug in which Allocations on the Payment level were not deleted when deleting a Recurring Donation. 

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by vmartinov-sforg** [comment]
@KietTruongSFDO  Can you please add a github issue and reference it in the Issues Closed section.

**Comment by KietTruongSFDO** [comment]
> @KietTruongSFDO Can you please add a github issue and reference it in the Issues Closed section.Also add a Testing Notes section in the header.

@vmartinov-sforg Issues are handled differently in NPSP. NPSP also does not use Testing Notes in their PRs.

**Comment by annejackson** [comment]
@force2b  did you want to look at this one? It deals with Recurring Donations.

**Comment by KietTruongSFDO** [comment]
**lurch: attach W-033708

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087vYVQAY" target="_blank">W-033708</a>

**Pull request merged**
