### PR TITLE
Enhanced Recurring Donations - Work in Progress (Part 1)

### PR DESCRIPTION
**Pull request by force2b**
# Critical Changes

# Changes

- New fields have been added for the upcoming initial pilot release of Enhanced Recurring Donations. For now, these fields are not used at all by current Recurring Donations functionality and should not be added to page layouts.
- Because the Enhanced Recurring Donations pilot is still a work in progress and will have very limited functionality, Admins should **not** attempt to manually change the `IsRecurringDonations2Enabled__c` custom setting field value in their orgs. Doing this outside of a controlled pilot in a Sandbox environment will very likely create issues with your current Recurring Donations (v1) data.
- We added Feature Telemetry for the upcoming initial pilot release of Enhanced Recurring Donations. No data will be collected until this functionality is enabled at a later date. NPSP Feature Telemetry collects feature and usage metrics when customers use our products. We use this information to understand the level of usage and adoption of various NPSP features. No personally identifiable information is collected through NPSP Feature Telemetry. Read more about NPSP Telemetry here: https://powerofus.force.com/s/article/NPSP-Feature-Telemetry.

# Issues Closed

# New Metadata

New Fields:
- npe03__Recurring_Donation__c.InstallmentFrequency__c
- npe03__Recurring_Donation__c.PaymentMethod__c
- npe03__Recurring_Donation__c.RecurringType__c
- npe03__Recurring_Donation__c.StartDate__c
- npe03__Recurring_Donation__c.Status__c
- npe03__Recurring_Donations_Settings__c.InstallmentOppStageName__c
- npe03__Recurring_Donations_Settings__c.IsRecurringDonations2Enabled__c

Feature Parameters:
- IsEnabled_RecurringDonations2

# Deleted Metadata

### CODE REVIEW

**Comment by force2b** [comment]
@rponti-sforg This PR is a culmination of the RD2 related child PR's that have been merged into this parent branch so far. I don't see any other RD2 child PR's being merged today, so I think at this point this PR should be ready for a quick review (considering that everything has been QA'd individually at this point) and a merge later today or tomorrow am. What do you think?

Also, there's no specific work item for this since it's just a collection of previously merged PR's/work items.

**Comment by force2b** [comment]
@sam-knox Would you mind reviewing the PR comment for this one since it's merging into master?

**Comment by rponti-sforg** [comment]
> @rponti-sforg This PR is a culmination of the RD2 related child PR's that have been merged into this parent branch so far. I don't see any other RD2 child PR's being merged today, so I think at this point this PR should be ready for a quick review (considering that everything has been QA'd individually at this point) and a merge later today or tomorrow am. What do you think?
> 
> Also, there's no specific work item for this since it's just a collection of previously merged PR's/work items.

No problem Mike.  So, to make sure we are thinking the same thing, you want me to review this PR to ensure the correct RD2 child PRs and their respective WI's have been tested (I am not testing ... just making sure WI has test details documented), Closed, and merged into feature/RD2?   Once that is done, I can merge this PR itself, correct?

**Comment by force2b** [comment]
@rponti-sforg Yes. I think that would cover it. There isn't a lot in this PR other than new fields, which we would **not** want current RD1 users to use. Also, you'll have to approve this PR before you can merge it.

**Comment by rponti-sforg** [comment]
@force2b The last commit made looks to be for BDI Advanced Mapping.  I am assuming this was done in order to add new RD2 fields to the BDI mix.  Just want to make sure... this will not impact current BDI now ... but will need to be tested in future when code is fully integrated?

**Pull request merged**
