### PR TITLE
🥐 Rollups: The Next Generation

### PR DESCRIPTION
**Pull request by force2b**
# Critical Changes

Rolling up donor data is an essential part of fundraising with the Nonprofit Success Pack. And since every nonprofit is unique, it is especially important that you're able to roll up exactly the data you need, and to the right records. With Customizable Rollups, you can create as many custom rollups as you need and define their process, filters, and where they roll up to. And as if that wasn't enough, you can now roll up Payments in addition to Opportunities, AND roll up Contact level soft credits to their parent Account. And as an added bonus, we now support Advanced Currency Management with Dated Exchange Rates for organizations with Customizable Rollups enabled. 

Customizable Rollups are available as part of NPSP with the Household Account Model. And when you enable Customizable Rollups, we will automatically convert your existing User Defined Rollups and the 87 out-of-box NPSP rollups, into Customizable Rollups. 
 
**To take advantage of the new Customizable Rollups, you need to enable it in your org.** Enabling Customizable Rollups makes some changes that are important to review and understand before turning this feature on. Here are the high level changes. 

* Existing Rollups are converted to new Customizable Rollups 
* Existing Rollup settings (in NPSP Settings) are removed and saved as metadata 
* New Rollup Settings appear in NPSP Settings under Donations 

For complete details, see this [doc](https://powerofus.force.com/NPSP_Customizable_Rollups_Considerations). 

# Changes

- A new **Recalculate Rollups** button is available for the Contact, Account, and General Accounting Unit page layouts. The button recalculates all rollups for that specific object using either the legacy Rollups engine or the new Customizable Rollups (if enabled). You will need to manually add the button to the appropriate Page Layouts to ensure that it is visible to users.

# Issues Closed

* #1978
* #1952 
* #1805
* #304
* #1912
* #2708
* #2804
* #2704
* #2637
* #2494
* #1541
* #2704
* #1296

**Power of Us HUB Ideas**
* [1017](https://powerofus.force.com/hub-ideas/1017) - Payment Rollups to Contact and Account - hard credits only
* [1275](https://powerofus.force.com/hub-ideas/1275) - Allow for "Accrual" vs. "Cash" accounting in NPSP setup/rollups/reports - Cash Accounting
* [1192](https://powerofus.force.com/hub-ideas/1192) - Allow logic for User Defined Rollups to be separate from standard NPSP rollups
* [1179](https://powerofus.force.com/hub-ideas/1179) - Filters for User Defined Rollups
* [1280](https://powerofus.force.com/hub-ideas/1280) - Create Rollups that Work off of Designated Fiscal Year over Closed Date
* [1070](https://powerofus.force.com/hub-ideas/1070) - Allow User Defined Rollups to ignore excluded Opportunity Record Types & Types
* [1224](https://powerofus.force.com/hub-ideas/1224) - Give the option to include pledges in donor statistics
* [1244](https://powerofus.force.com/hub-ideas/1244) - Create both CY & FY roll ups as standard deployment
* [1221](https://powerofus.force.com/hub-ideas/1221) - Rollup field in the Recurring Donation to calculate when the RD is closed
* [1165](https://powerofus.force.com/hub-ideas/1165) - count pledged memberships as members
* [1145](https://powerofus.force.com/hub-ideas/1145) - Include partially-paid pledges in donor roll-up statistics
* [1079](https://powerofus.force.com/hub-ideas/1079) - Recurring donation recalculations should only count Posted and Pledged opps
* [1073](https://powerofus.force.com/hub-ideas/1073) - Allow display of soft credits in the account layout
* [1045](https://powerofus.force.com/hub-ideas/1045) - Largest Gift Date
* [1050](https://powerofus.force.com/hub-ideas/1050) - First Gift Amount

# New Metadata

* Rollup__mdt.object
* Filter_Group__mdt.object
* Filter_Rule__mdt.object
* Customizable_Rollup_Settings__c.object
* npo02__Households_Settings__c.Use_Dated_Conversion_Rates__c (field)
* CMT_FilterRule.cls
* CMT_FilterRuleEvaluation_SVC.cls
* CMT_FilterRuleEvaluation_TEST.cls
* CMT_FilterRuleUI_SVC.cls
* CMT_FilterRule_SEL.cls
* CMT_FilterRule_TEST.cls
* CMT_MetadataAPI.cls
* CMT_MetadataAPI_TEST.cls
* CMT_UnitTestData_TEST.cls
* CRLP_AccountSkew_BATCH.cls
* CRLP_AccountSkew_SoftCredit_BATCH.cls
* CRLP_Account_BATCH.cls
* CRLP_Account_SoftCredit_BATCH.cls
* CRLP_Batch_Base.cls
* CRLP_Batch_Base_NonSkew.cls
* CRLP_Batch_Base_Skew.cls
* CRLP_ConfigBuilder_SVC.cls
* CRLP_ConfigBuilder_TEST.cls
* CRLP_ContactSkew_BATCH.cls
* CRLP_ContactSkew_SoftCredit_BATCH.cls
* CRLP_Contact_BATCH.cls
* CRLP_Contact_SoftCredit_BATCH.cls
* CRLP_Debug_UTIL.cls
* CRLP_DefaultConfigBuilder.cls
* CRLP_DefaultConfigBuilder_SVC.cls
* CRLP_DefaultConfigBuilder_TEST.cls
* CRLP_FiscalYears.cls
* CRLP_FiscalYears_TEST.cls
* CRLP_GAU_BATCH.cls
* CRLP_Operation.cls
* CRLP_Operation_SVC.cls
* CRLP_Operation_TEST.cls
* CRLP_Query_SEL.cls
* CRLP_Query_SEL_TEST.cls
* CRLP_RDSkew_BATCH.cls
* CRLP_RD_BATCH.cls
* CRLP_RecalculateBTN_CTRL.cls
* CRLP_RecalculateBTN_TEST.cls
* CRLP_Rollup.cls
* CRLP_RollupAccount_SVC.cls
* CRLP_RollupAccount_TEST.cls
* CRLP_RollupBatch_SVC.cls
* CRLP_RollupCMT.cls
* CRLP_RollupContact_SVC.cls
* CRLP_RollupContact_TEST.cls
* CRLP_RollupGAU_SVC.cls
* CRLP_RollupGAU_TEST.cls
* CRLP_RollupProcessingOptions.cls
* CRLP_RollupProcessor_SVC.cls
* CRLP_RollupQueueable.cls
* CRLP_RollupRD_SVC.cls
* CRLP_RollupRecurringDonation_TEST.cls
* CRLP_RollupScheduler_TEST.cls
* CRLP_RollupSoftCredit_SVC.cls
* CRLP_RollupSoftCredit_TEST.cls
* CRLP_RollupUI_SVC.cls
* CRLP_RollupUI_TEST.cls
* CRLP_Rollup_SEL.cls
* CRLP_Rollup_SEL_TEST.cls
* CRLP_Rollup_SVC.cls
* CRLP_Rollup_SVC_TEST.cls
* CRLP_Rollup_TDTM.cls
* CRLP_SkewDispatcher_BATCH.cls
* CRLP_VRollupHandler.cls
* STG_PanelCustomizableRollup_CTRL.cls
* UTIL_CurrencyCache.cls
* UTIL_CurrencyCache_TEST.cls
* UTIL_CurrencyConversion.cls
* UTIL_CurrencyConversion_TEST.cls
* UTIL_PlatformCache.cls
* UTIL_OrgTelemetry_SVC.cls
* CRLP_RollupAccount_BTN.page
* CRLP_RollupContact_BTN.page
* CRLP_RollupSetup.page
* CRLP_FilterGroup.lightning
* CRLP_Rollup.lightning
* CRLP_RollupApp.lightning
* CRLP_RollupsContainer.lightning
* CRLP_SelectField.lightning
* CRLP_Tooltip.lightning

# Deleted Metadata

* ALLO_RollupBTN_CTRL

### CODE REVIEW

**Comment by force2b** [comment]
image

**Comment by allisonletts** [comment]
bitmoji
Soooo excited to dig into this!

Looks like the doc linked for more details (the last line of the Critical Changes section) isn't visible to the public yet--I'm getting a 404. Is that intentional?

 https://powerofus.force.com/articles/Resource/Things-to-Consider-Before-Enabling-Cust-Rollups

**Comment by bethbrains** [comment]
Correct, intentional. :)

**Comment by carlosgallardosfdc** [comment]
@bethbrains  If intentional would anyone know when the doc will go live? Or is this featured delivered, but not ready to go live? Trying to figure out how to enable it in sandbox to do some testing.

**Comment by judisohn** [comment]
@carlosgallardosfdc The pull request has been merged, but not released yet. The doc will go live on the day of the sandbox release when the managed package is created (scheduled for 5/23). What's in this pull request is what will be in the release notes, so that's why we have a dead link for now. Sorry for any frustration that causes. We know the wait will be worth it. :-)

**Comment by carlosgallardosfdc** [comment]
@judisohn No no frustration. Just excited to test. After I wrote my message I was like oh this is just the pull request and not actually went live with the NPSP upgrade from yesterday. Thanks for the clarification though. Much appreciated!

cc: @allisonletts

**Comment by JeffB-Mountaineers** [comment]
The link to the "doc" is broken: https://powerofus.force.com/articles/Resource/Things-to-Consider-Before-Enabling-Cust-Rollups

**Comment by njjc** [comment]
I guess this is what happens when we publicly share pull requests :) I've removed the broken link to the doc, we'll put it back when it's published.

**Comment by JeffB-Mountaineers** [comment]
Many thanks! These are exactly what we need!

**Comment by ellemckay** [comment]
@carlosgallardosfdc Do you know when Customizable Rollups will be available in production?

**Comment by carlosgallardosfdc** [comment]
@ellemckay From what I understand reading through the NPSP Release Announcements, version 3.129 was going to be released tonight 5/29, but I think they needed to work on some "small, critical changes" before the full release to Prod tonight. So new version 3.130 push to sandboxes will happen tonight and then 3.130 push to Production environments tomorrow night, 5/30.

Read here if you have access to Power of Us Hub (https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000D9Qr).

Also once pushed Customizable Rollup functionality is not activated immediately. You need to activate manually, but as always first test in Sandbox!

**Pull request merged**
