### PR TITLE
Changing Default GAU lookup in settings to use UTIL_InputField

### LINKED ISSUE #3755: The search icon for Default General Accounting Unit in Allocation Settings is no longer visible
As a result, it's impossible to select a GAU to use as the default GAU.

image

### PR DESCRIPTION
**Pull request by lparrott**
# Critical Changes

# Changes

# Issues Closed

Fixes #3755 

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by force2b** [comment]
**lurch: attach W-029435

**Comment by force2b** [comment]
@rponti-sforg Would you mind QA'ing this small fix before I merge?

**Comment by rponti-sforg** [comment]
> @rponti-sforg Would you mind QA'ing this small fix before I merge?

Happy to... Sorry for the delay in responding.

**Comment by force2b** [comment]
Thanks @rponti-sforg. You're free to merge once QA is complete.

**Comment by rponti-sforg** [comment]
QE testing is complete for this PR.

For further testing details, see: https://foundation.lightning.force.com/lightning/r/agf__ADM_Work__c/a2x1E000007fP7SQAU/view

Merging PR and deleting branch.

**Pull request merged**
