### PR TITLE
Delete a Contact and Leave Empty Account (with Contact Delete Override enabled)

### PR DESCRIPTION
**Pull request by RadSFDeveloper**
# Critical Changes

# Changes

- When deleting the only Contact in a Household, you can now choose to leave the Account empty.  Alternatively, you can choose to delete the Account (existing behavior). Thank you Beth Breisnes for this contribution! 

# Issues Closed

# New Metadata
- DeleteAccount (CustomLabel)
- DeleteContactLeaveAccount (CustomLabel)

# Deleted Metadata

### CODE REVIEW

**Comment by RadSFDeveloper** [comment]
@smarovich , please can you review Changes section?
Additionally, documentation for "NPSP: Deleting Accounts, Contacts, and Other Records" > "What happens when I delete a Contact (with Contact Delete Override enabled)?" needs an update based on  the most recent modifications. Thank you!

**Comment by RadSFDeveloper** [comment]
Beth Breisnes, thank you for your contribution! We made some minor changes with regards to how the platform deals with navigation with regards to Classic vs Lex. It took a while to find and investigate the issue during code review, so we went ahead and made the change. Please note this issue was not introduced by your changes.

**Comment by smarovich** [comment]
Hi @RadSFDeveloper, I updated the Changes section and will update the doc as well. Thanks for the heads up!

**Comment by judisohn** [comment]
@jjbennett @RadSFDeveloper I finished up testing in both LEX and Classic and couldn't find anything out of line (except for noting that we should ultimately remove the override pages associated with Contacts & Orgs - one absolutely doesn't work) and a suggested enhancement to avoid 'Anonymous Household' - other than that, good by me! Thanks for doing a great job with this community contribution, Radmila!

**Pull request merged**
