### PR TITLE
Write-Off Payments Page: Disable button on click to prevent accidental multiple clicks

### PR DESCRIPTION
**Pull request by npsp-reedestockton**
# Critical Changes

# Changes
- NPSP disables the Write Off Payments button after the first time a user clicks it. Prior to this change, multiple clicks on the button would produce multiple payment records.

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by sam-knox** [comment]
@npsp-reedestockton - Other than the release notes, is there anything else I should review?

**Comment by npsp-reedestockton** [comment]
@sam-knox release notes was the only intended review item for you.  I'll be more explict with an @mention in the future.

**Comment by npsp-reedestockton** [comment]
**lurch: attach W-033803

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087vgPQAQ" target="_blank">W-033803</a>

**Comment by Julian88Tex** [comment]
merged and WI has been closed: https://foundation.lightning.force.com/lightning/r/agf__ADM_Work__c/a2x1E0000087vgPQAQ/view

**Pull request merged**
