### PR TITLE
create dev_multicurrency org config

### PR DESCRIPTION
**Pull request by Julian88Tex**
# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by Julian88Tex** [comment]
@force2b as a test mind just running this command and making sure the org created is multi-currency?

`cci flow run qa_org --org dev_multicurrency`

**Comment by force2b** [comment]
@Julian88Tex Actually the commands to use this new definition would something like:
```
cci org scratch dev_multicurrency mcdev
cci flow run qa_org mcdev
```

**Comment by Julian88Tex** [comment]
> @Julian88Tex Actually the commands to use this new definition would something like:
> 
> ```
> cci org scratch dev_multicurrency mcdev
> cci flow run qa_org --org mcdev
> ```

Yeah, if you want to create a separate scratch with its own name yes which I would agree isn't a bad thing to test, but since I have also added it to the cumulusci.yml org list it will be a default org as well that doesn't require being created.

Some documentation on this part of it: https://cumulusci.readthedocs.io/en/latest/tutorial.html

"One important thing to note is that CumulusCI automatically creates all named scratch org configs in your project’s keychain for you."

**Comment by Julian88Tex** [comment]
> Worked great. Thanks for creating this!

@force2b my pleasure and thanks for testing! Was wondering, do we indeed typically wait for infrastructure to do an approval on this or can I go ahead and merge?

**Comment by force2b** [comment]
@Julian88Tex Typically yes. @davidmreed Would you mind doing a quick review on this when you get a chance?

**Comment by Julian88Tex** [comment]
@davidmreed @force2b  Thanks!

**Pull request merged**
