### PR TITLE
Consolidation of various Allocation bugs

### PR DESCRIPTION
**Pull request by KietTruongSFDO**
# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by markross-sfdo** [comment]
@KietTruongSFDO @jbrandolinisf Can I get a formal confirmation that this PR doesn't contain anything but invisible-to-users Payment Allocation bug fixes? No behavioral changes?

**Comment by KietTruongSFDO** [comment]
@markross-sfdo There's changes to how various aspects of the Payment Allocation sync works, but they're not new functionality (Bug fixes like you said). I don't think we're supposed to have PR text for Payment Allocation bug fixes, right?

**Comment by davisagli** [comment]
@beAGoodQE why did you restore the branch after deleting it? Is it still in use?

**Comment by davisagli** [comment]
@KietTruongSFDO I am deleting the `feature/kiet/IncludeInactiveGAUOnAllocCreation` branch which appears to have been included in this merge. If you combine multiple branches together for QA and merge like this, please remember to delete all the included feature branches once the merge is done.

**Comment by KietTruongSFDO** [comment]
@davisagli I'll keep that in mind for the future. I've also deleted a few other branches that are no longer being used.  Sorry about that!

**Comment by KietTruongSFDO** [comment]
Hi @markross-sfdo and @lianeyee Can you guys double check these change notes? Thanks!

**Pull request merged**
