### PR TITLE
Added edit mode from Batch Templates record view

### PR DESCRIPTION
**Pull request by randi274**
# Critical Changes

# Changes
- Record can be edited from View mode
- When record is edited or created, page changes to Read Only
- When record is edited, duplicate records are not created.
- Change references of displayTotalPrompt to enableTotalEntry to map up to 
# Issues Closed

# New Metadata
Labels: bgeBatchTemplateEdit, bgeBatchTemplateMoveFieldDown, bgeBatchTemplateMoveFieldUp, bgeBatchTemplateNew

# Deleted Metadata

### CODE REVIEW

**Comment by randi274** [comment]
**lurch: attach W-025915

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYBPrAAP" target="_blank">W-025915</a>

**Comment by randi274** [comment]
**lurch: attach W-026741

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYCUtAAP" target="_blank">W-026741</a>

**Pull request merged**
