### PR TITLE
Reverted the CMT creation in the post install. 

### PR DESCRIPTION
**Pull request by KietTruongSFDO**
# Critical Changes

# Changes
* We reverted the installation and update flow previously introduced for the custom metadata type, Opportunity Stage to State Mapping. These changes are intended for a future release and should have no visible impact on your org.
# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by melissabarber** [comment]
Hey there @KietTruongSFDO! Just a quick, minor request for the top section of your PRs. Please be sure to use the "- " markdown for a bullet instead of "* ". It's not a noticeable different in the individual PRs, but when the information gets pulled into the Release Notes, it messes up the spacing between the larger list of bullets. Thanks!

**Comment by davisagli** [comment]
@melissabarber you'll probably want to remove the release notes for both #4455 and this PR since the feature was both added and then removed since the the last release.

**Comment by KietTruongSFDO** [comment]
> Hey there @KietTruongSFDO! Just a quick, minor request for the top section of your PRs. Please be sure to use the "- " markdown for a bullet instead of "* ". It's not a noticeable different in the individual PRs, but when the information gets pulled into the Release Notes, it messes up the spacing between the larger list of bullets. Thanks!

Sorry about that, @melissabarber. I'll keep that in mind for the future. @davisagli is correct though, it makes sense to remove the change notes for the two PR since it would probably look strange in the overall release notes.

**Comment by lianeyee** [comment]
> > Hey there @KietTruongSFDO! Just a quick, minor request for the top section of your PRs. Please be sure to use the "- " markdown for a bullet instead of "* ". It's not a noticeable different in the individual PRs, but when the information gets pulled into the Release Notes, it messes up the spacing between the larger list of bullets. Thanks!
> 
> Sorry about that, @melissabarber. I'll keep that in mind for the future. @davisagli is correct though, it makes sense to remove the change notes for the two PR since it would probably look strange in the overall release notes.

That was my bad, @melissabarber. The original note wasn't bulleted so I added one and mistakenly used the *. Really sorry about the extra trouble.

Having two release notes for the two PRs is odd. For historical clarity, do we consider manually consolidating them into one? "We introduced and then reverted an installation and update flow for the custom metadata type, Opportunity Stage to State Mapping. These changes are intended for a future release and should have no visible impact on your org." I'm not wedded to including even one note--just making sure everything is accounted for.

**Comment by melissabarber** [comment]
Thanks, all! The bullet format request is super nitpicky and really only
noticeable when the PR gets sucked into Release Notes. No worries for
missing it. Perhaps we should add that formatting tip to the Update Release
Notes in Github (for Developers) doc?

Look forward to hearing more about best practices for PRs which were rolled
back.

**Pull request merged**
