### PR TITLE
RD2: Create one Schedule per RD during legacy to enhanced RD data migration

### PR DESCRIPTION
**Pull request by RadSFDeveloper**
# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by RadSFDeveloper** [comment]
**lurch: attach W-037458

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HoVKQA0" target="_blank">W-037458</a>

**Comment by RadSFDeveloper** [comment]
@Julian88Tex , changes are read for testing.

**Comment by Julian88Tex** [comment]
Testing has passed and WI has been merged to master: https://foundation.lightning.force.com/lightning/_classic/%2Fa2x1E000001HoVKQA0

**Pull request merged**
