### PR TITLE
Auto close Opportunity on Overpayment

### LINKED ISSUE #3824: When Payment Amount is larger than the related Opportunity Amount, marking Payment as Paid is not auto-closing Opportunity
Issue:
If the Amount of the Payment is higher than the Amount of the Opportunity, the Opty stage is not changed to a Closed/Won status when the Payment record is marked Paid. 

Steps to Repro:
1. Create an open stage Opportunity for $40. Notice the resulting Payment record for $40. 
2. Open Payment record and click Edit. 
3. Change Payment Amount to $42, and mark as Paid. Enter today's date as the Payment Date.
4. Go back to Opty and notice the stage of the Opty is still open, and has not been changed to Posted or any Closed/Won value.

Thanks to @bethbrains for catching/reporting this one.

### PR DESCRIPTION
**Pull request by KietTruongSFDO**
Prior to this change, Opportunities would automatically close if the total paid payment amounts equaled the Opportunity Amount.  This change extends this functionality to also auto-close the Opportunity if the total paid payments exceed the Opportunity Amount.

# Critical Changes

# Changes
- We changed the way NPSP handles Opportunities where the amount of Paid Payments is more than the original Opportunity Amount. If a Payment is marked as paid, and it pushes the total amount of Payments over the Opportunity Amount, the Opportunity is automatically closed. Its Stage is changed to the setting found on the NPSP Settings page (Donations > Payments > Opportunity Stage for When Fully Paid). Previously, the Opportunity stage would not automatically be set to a Closed/Won stage.
# Issues Closed

- Fixes #3824 

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by KietTruongSFDO** [comment]
**lurch: attach W-030860

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fQvSQAU" target="_blank">W-030860</a>

**Comment by jbrandolinisf** [comment]
@KietTruongSFDO  - Just amending for one thing.  Can you add a test that checks the > scenario as well as the equal scenario now?

**Comment by KietTruongSFDO** [comment]
> @KietTruongSFDO - Just amending for one thing. Can you add a test that checks the > scenario as well as the equal scenario now?

I've added the test methods into this PR now.

**Pull request merged**
