### PR TITLE
Feature/vbeck description updates

### PR DESCRIPTION
**Pull request by watersbeck**
# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by watersbeck** [comment]
Hey Sam, I updated the description field to match the help text for all help text strings I previously updated. Since description is pushed in upgrades, we're using this to let customers know what the updated help text strings are, so they can manually update them if they choose. Can you put your eagle eyes on this and make sure the descriptions match the help text? Thanks!

**Comment by sam-knox** [comment]
@watersbeck - Can do!

**Comment by watersbeck** [comment]
Thanks Sam! Working on cleaning up errors and rebuilding ...

**Comment by sam-knox** [comment]
Should I hold off on reviewing, or is it ready?

**Comment by watersbeck** [comment]
Ok Sam, I've made the suggested changes. Good catches, all of them! Ready for you to recheck.

**Comment by force2b** [comment]
@sam-knox Do you think the PR Description should include a note about the fact that the packaged field "Description" values have been updated to match the InlineHelpText?

**Comment by sam-knox** [comment]
Yes, probably so. I'll write a brief release note.

**Pull request merged**
