### PR TITLE
NPSP SFDC L10n Team First Delivery for Translations via Git

### PR DESCRIPTION
**Pull request by GloryChoe**
Hi NPSP team, I'm Glory Choe, Localization Program Manager at SFDC. This PR includes:

Massive translation improvements made by SFDC Localization team
First delivery of translation files via Git

Please reach out to Mary Pustejovsky for any internal questions.

Thanks,
Glory

### CODE REVIEW

**Comment by judisohn** [comment]
**lurch: add

**Comment by judisohn** [comment]
Thanks @GloryChoe!

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C8nRQAS" target="_blank">W-035008</a>

**Comment by GloryChoe** [comment]
Hi @LurchTheButler, letting you know that we made some translation improvements based on Localization Linguistic QA testing so I've committed the changes.

**Pull request closed without merging**
