### PR TITLE
Update gem0 namespace to gem

### PR DESCRIPTION
**Pull request by bdvorachek**
- We updated the Advancement namespace default value to support the final namespace for our sister product, GEM. This should have no impact on NPSP functionality.

# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

# Testing Notes
When gem is installed and this PR is applied, all apex tests from the NPSP package should pass. That part of testing is only possible after a release has been cut.

### CODE REVIEW

**Comment by bdvorachek** [comment]
**lurch: attach W-033245

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087uwgQAA" target="_blank">W-033245</a>

**Comment by bdvorachek** [comment]
Hi @force2b - We're trying to get this change in the next release of Cumulus to go along with the GEM release. Are you able to review this so we can make that cutoff? Thanks.

**Comment by annejackson** [comment]
@smarovich and @markross-sfdo - please see the changes section in this PR, I know we have done this before when we went to the gem0 namespace if you want to look back on past "release notes".

**Comment by annejackson** [comment]
Merging since code review(s) passed. Will test with a beta release.

**Pull request merged**
