### PR TITLE
Showing stack trace in debug log.

### PR DESCRIPTION
**Pull request by ceiroa**
I did this for HEDAP and it helped me debug an issue that was otherwise hard to track. I thought it might be worth it adding it to NPSP.

### CODE REVIEW

**Comment by ceiroa** [comment]
@davidhabib ~ would you mind taking a quick look?

**Comment by davidhabib** [comment]
@jlantz why didn't this pull request generate a build?

**Comment by ceiroa** [comment]
It did build: http://ci.salesforcefoundation.org/view/feature/job/Cumulus_feature/3555/

I think it's just that @njjc just merged another pull request, and it's now building the dev-to-feature jobs.

**Comment by davidhabib** [comment]
why isn't it showing the "waiting for build xxxx to complete" message?

**Comment by njjc** [comment]
Because it's not correctly referencing the issue number perhaps? feature/*1234*-foo

**Pull request merged**
