### PR TITLE
Feature/rollups  filter rule list access check error

### LINKED ISSUE #3244: Customizable Rollups: Persistent Java Script error on various pages
An error message is appearing at the bottom of a variety of pages related to Customizable Rollup settings, filter groups, and on the new rollup page:

_This page has an error. You might just need to refresh it. Access Check Failed! AttributeSet.get(): attribute 'filterRuleList' of component 'markup://npsp:CRLP_RollupsContainer {6:0}' is not visible to 'markup://aura:if {94:0}'. Failing descriptor: {aura:if}_

screen shot 2018-06-01 at 10 02 09 am

Happens in both Lightning and Classic. Appears even after logging out/in, Incognito browser or not, disable/enable CRLP's, etc. Org is a production org originating as Trail. Received CRLP's via general production push.

So far this has not be replicated in any other org as far as we know. 

Error message appears to remain the same regardless of the page, although @randi274  believes she saw a different error message once when logged into my org.

### PR DESCRIPTION
**Pull request by randi274**
# Critical Changes

# Changes
- Intended fix for lightning component access error, and cleaning up unused CSS. 
# Issues Closed

Fixes #3244 

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by force2b** [comment]
@bethbrains Can you clarify what is being changed here? There's a lot of code changes, but I'm not necessarily clear on what to test for.

**Comment by randi274** [comment]
@force2b only the last two commits are from this branch. I made this branch off of feature/rollups__fg-ui-tweaks, and it's clearer when you see the diff between these two branches. I'm a little unclear why this didn't seem to update when that was merged in though?

**Comment by force2b** [comment]
Odd. I changed the destination to `master` and then back to `feature/rollups`. That seems to have fixed the problem.

**Comment by force2b** [comment]
Is there a way to reproduce the initial error that this PR fixes?

**Comment by randi274** [comment]
Unfortunately, no. It's only happening in Cori's org so far, and we haven't been able to create it in one of our orgs yet. However this is extra code that should be cleaned up anyway. I'm hoping this will fix it, but I'm unable to test this before the patch deployment.

**Pull request merged**
