### PR TITLE
Contact merge slds styling

### PR DESCRIPTION
**Pull request by dospromptman**
*This is dependent on #1946 -- The diff will be cleaner if you merge that first*

# Warning
# Info

The Contact Merge page has been updated to use Lightning styles.

# Issues

### CODE REVIEW

**Comment by njjc** [comment]
**lurch: review visualforce

**Comment by njjc** [comment]
**lurch: review apex visualforce

**Comment by njjc** [comment]
lurch???

**Comment by kbromer** [comment]
Heroku idled him - in theory we can just use the pull request template for this now though, so that might be okay- lets discuss in standup

**Pull request merged**
