### PR TITLE
UI - Allow configurable batch size for RecurringDonations

### PR DESCRIPTION
**Pull request by kofijohnson**
# Critical Changes

# Changes
The batch size for the Recurring Donations nightly scheduled job and bulk data process was previously hard coded to 50. You can now configure this value using the new **Recurring Donation Batch Size** field located in **NPSP Settings | Recurring Donations**. If this field is left blank, it will default to 50.

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by kofijohnson** [comment]
@smarovich we added a new field "Recurring Donation Batch Size" on the "Nonprofit Success Pack Settings -> Recurring Donations." The new field allows the end user to configure the Recurring Donations batch size. We probably need to put it in the release note. Please let me know how I can help.

**Comment by smarovich** [comment]
Hi @kofijohnson, sorry for the delay. Yes, that should be in the release notes. Is there descriptive (or help) text with the new field? If not, we should add something like this "Determines the number of records processed at a time in the Recurring Donations nightly batch. Default is 50."

**Comment by smarovich** [comment]
I also updated the release notes. Please let me know if I need to make any changes. Thanks!

**Comment by kofijohnson** [comment]
@smarovich the release note is good. Thank you!

**Comment by davidhabib** [comment]
@kofijohnson while manually testing, I am seeing some weird behavior.  I can edit RD batch size and set it to something like 1000.  If I refresh the page, I can still see it at 1000.  Now I got to edit the page, and it shows empty for the batch size.

**Comment by davidhabib** [comment]
999 seems to work.  i wonder if it is the comma that is getting put in 1,000.

**Comment by kofijohnson** [comment]
@davidhabib I will take a look. Thanks!

**Comment by davidhabib** [comment]
@RadSFDeveloper looks like the namespace tests are failing, due to not correctly namespacing some of the new properties you added.

Failing Tests
2018-02-26 10:42:20: --------------------------------------------------------------------------------
2018-02-26 10:42:20: 1: STG_PanelHealthCheck_TEST.testVerifyRecordTypes - Fail
2018-02-26 10:42:20: 	Message: npsp.UTIL_Describe.SchemaDescribeException: Invalid object name 'Allocations_Settings__c'
2018-02-26 10:42:20: 	StackTrace: Class.npsp.UTIL_Describe.fillMapsForObject: line 65, column 1
Class.npsp.UTIL_Describe.fillFieldMapsForObject: line 74, column 1
Class.npsp.UTIL_Describe.getFieldLabel: line 267, column 1
Class.npsp.STG_PanelHealthCheck_CTRL.checkRecordTypeId: line 528, column 1
Class.npsp.STG_PanelHealthCheck_CTRL.checkMultiRecordTypeIds: line 508, column 1
Class.npsp.STG_PanelHealthCheck_CTRL.verifyRecordTypes: line 456, column 1
Class.npsp.STG_PanelHealthCheck_TEST.testVerifyRecordTypes: line 476, column 1
2018-02-26 10:42:20: 2: STG_SettingsManager_TEST.testPanelHealthCheck - Fail
2018-02-26 10:42:20: 	Message: npsp.UTIL_Describe.SchemaDescribeException: Invalid object name 'Allocations_Settings__c'
2018-02-26 10:42:20: 	StackTrace: Class.npsp.UTIL_Describe.fillMapsForObject: line 65, column 1
Class.npsp.UTIL_Describe.fillFieldMapsForObject: line 74, column 1
Class.npsp.UTIL_Describe.getFieldLabel: line 267, column 1
Class.npsp.STG_PanelHealthCheck_CTRL.checkMultiRecordTypeIds: line 511, column 1
Class.npsp.STG_PanelHealthCheck_CTRL.verifyRecordTypes: line 456, column 1
Class.npsp.STG_PanelHealthCheck_CTRL.runAllDetections: line 162, column 1
Class.npsp.STG_PanelHealthCheck_CTRL.runDetector: line 101, column 1
Class.npsp.STG_SettingsManager_TEST.testPanelHealthCheck: line 1014, column 1
2018-02-26 10:42:20: 3: TDTM_DMLgt200_TEST.test_addresses - Fail
2018-02-26 10:42:20: 	Message: System.LimitException: Apex CPU time limit exceeded
2018-02-26 10:42:20: 	StackTrace: Class.npsp.TDTM_ObjectDataGateway.getClassesToCallForObject: line 71, column 1
External entry point
Class.npsp.TDTM_TriggerHandler.run: line 93, column 1
Trigger.npsp.TDTM_Account: line 34, column 1

**Comment by kofijohnson** [comment]
@davidhabib, I just did a test, and I found out that this bug is everywhere we have input text in the NPSP Settings. I think we should create a bug ticket to fix all the inputs. Thoughts?

**Comment by davidhabib** [comment]
Yes, @kofijohnson please enter a new bug and say that it affects all settings.  Definetly an edge case, because all of our settings should have much lower numbers!  so not high priority.  thanks.

**Pull request merged**
