### PR TITLE
Feature/getting started page label changes

### PR DESCRIPTION
**Pull request by cpurodriguez**
# Critical Changes
* Fixing Typos on Labels
# Changes
* Adding a link to the GH Download URL label
# Issues Closed

### CODE REVIEW

**Comment by cpurodriguez** [comment]
@cpolcyn 

I have one test failing from another module:

`RD_RecurringDonations_TEST2.testOpenEndedMonthlyEndDates
Stack Trace:
Class.RD_RecurringDonations_TEST2.testOpenEndedMonthlyEndDates: line 1094, column 1`

thoughts? 

cc @davidhabib @mdeleon0 @Sonhia19

**Comment by cpolcyn** [comment]
Failure message: System.AssertException: Assertion Failed: Expected: 12, Actual: 10

This needs to be fixed before merging. I don't really have insight to test content so this will need to be fixed by you or a member of NGO team.

**Comment by cpurodriguez** [comment]
@cpolcyn can you mention one of the NGO team here so I can engage with them?

**Comment by cpolcyn** [comment]
@davidhabib is the point person for NGO on this project I believe.

**Comment by cpurodriguez** [comment]
@cpolcyn thanks - I know he's out today (and probably monday too) @davidhabib let me know how you want to make this happen, I can comment out the assert until I a proper fix - let me know what works for you

**Comment by cpolcyn** [comment]
@cpurodriguez this test failure was just revealed today but has been in the code for some time, so it's not due to your changes. We are working to fix and once that is merged to master it will be merged here, then tests will run again and hopefully pass so we can merge.

**Comment by cpurodriguez** [comment]
@cpolcyn I was about to patch this by commenting out the line to make the test pass :) 
so your comment came right on time - 👍

**Pull request merged**
