### PR TITLE
LeadConversion ApexDoc and some class cleanup

### LINKED ISSUE #1308: ApexDocs comments for lead conversion, plus some cleanup work

### PR DESCRIPTION
**Pull request by kbromer**
Closes #1308

### CODE REVIEW

**Comment by mrbelvedere** [comment]
Can an admin approve this request for build?

**Comment by kbromer** [comment]
**mrbelvedere: approved**

**Comment by mrbelvedere** [comment]
OK, build is started.  You can view status at http://ci.salesforcefoundation.org/job/Cumulus_feature_ext/66.  If you get a 404, please try again later as the build might be queued.  I will update the build status on the pull request when the build is done

**Comment by mrbelvedere** [comment]
**success**: The build succeeded!, view the build at http://ci.salesforcefoundation.org/job/Cumulus_feature_ext/66/

**Comment by mrbelvedere** [comment]
**success**: The build succeeded!, view the build at http://ci.salesforcefoundation.org/job/Cumulus_feature_ext/66/

**Comment by kbromer** [comment]
@davidhabib or @ceiroa whenever you have a moment, this is just class comments, ready to go

**Comment by kbromer** [comment]
or @njjc too :)

**Comment by davidhabib** [comment]
Only if someone will get mine first which has been waiting for days!  I
can't get the build to run it!



On Jan 25, 2015, at 10:19 AM, Kevin Bromer <notifications@github.com> wrote:

@davidhabib <https://github.com/davidhabib> or @ceiroa
<https://github.com/ceiroa> whenever you have a moment, this is just class
comments, ready to go

—
Reply to this email directly or view it on GitHub
<https://github.com/SalesforceFoundation/Cumulus/pull/1309#issuecomment-71384302>
.

**Comment by kbromer** [comment]
@davidhabib Its not building because the classes aren't implementing the new interface method (getHelpText()) that they need to.  The implementing classes of that interface (the three verification services) need to provide an implementation of that method

**Pull request merged**
