### PR TITLE
Feature/hhnaming redesign

### LINKED ISSUE #2021: Case change of Contact name does not update Household Naming fields
hub thread: https://powerofus.force.com/0D58000002avhTF

### PR DESCRIPTION
**Pull request by davidhabib**
# Critical Changes

# Changes
* Custom Household Naming has been enhanced to support more name specifications
* You can now include {!Lastname} within the repeating firstnamespec which is demarcated with the surrounding {! }.  E.g., {! {!Firstname} {!LastName} } Family will give you John Doe & Jane Doe Family
* You can now include additional field references outside of the firstnamespec, which will refer to the first contact with that last name.  E.g., {!{!Salutation}} {Firstname} {Lastname} will give you Mr. & Mrs. John Doe
* You can now include fields through lookups fields on Contact.  E.g., {!{!Firstname}} {!Lastname} ({!Account.BillingCity}) would give you John & Jane Doe (Seattle)

# Issues Closed
#2021 
#1357 
#2341

### CODE REVIEW

**Comment by davidhabib** [comment]
@njjc The custom household naming enhancements are finished and ready for review and merge.  I still have a few other issues outstanding in AA, but they are all due to side effects when working within the Manage Household UI.

**Comment by njjc** [comment]
@davidhabib loaded into a DE org, tried a new default rule, and got this exception creating a new contact with just lastname populated:
screen shot 2016-11-18 at 1 15 54 pm
```
Error: Invalid Data. 
Review all error messages below to correct your data.
Apex trigger nictest.TDTM_Contact caused an unexpected exception, contact your administrator: nictest.TDTM_Contact: execution of AfterInsert caused by: System.NullPointerException: Attempt to de-reference a null object: Class.nictest.HH_NameSpec.strConFspec: line 323, column 1
```

**Comment by davidhabib** [comment]
@njjc fixed the error you found with not handling null object lookups.  also included the new help text and layout for the example name formats.  thanks.

**Comment by njjc** [comment]
Using the same default setting, I'm getting this error in the Manage HH UI: 
screen shot 2016-11-21 at 10 14 42 am

**Comment by njjc** [comment]
I ran tests manually here as our build system is extremely unreliable.

**Pull request merged**
