### PR TITLE
Add support for FeatureEnablement via the LMO for future pilot programs in NPSP

### PR DESCRIPTION
**Pull request by force2b**
# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by force2b** [comment]
**lurch: attach W-035556

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C9sxQAC" target="_blank">W-035556</a>

**Comment by rponti-sforg** [comment]
QE testing for this PR is complete.  Tests have passed.

For further testing details, see: https://foundation.lightning.force.com/lightning/r/agf__ADM_Work__c/a2x1E000001C9sxQAC/view

Merging PR and deleting branch.

**Comment by rponti-sforg** [comment]
Based on *Feature Test - Robot Prerelease* failure, which was is known and not critical to the overall build, merging will move forward with this PR.

**Pull request merged**
