### PR TITLE
Bug fix for underscheduled GAU allocation bug

### PR DESCRIPTION
**Pull request by KietTruongSFDO**
# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by markross-sfdo** [comment]
@KietTruongSFDO Should there be a GH issue for this bug? I think NPSP usually does Issues for bugs.

**Comment by judisohn** [comment]
@markross-sfdo @KietTruongSFDO No. If I'm understanding correctly, this is a bug of code that was not merged to master yet and therefore was never in customers' hands. Therefore, we don't need (or want) an issue for it. Thanks.

**Comment by KietTruongSFDO** [comment]
Hi @markross-sfdo and @lianeyee, can you guys take a look at these change notes real quick? Thanks!

**Comment by lianeyee** [comment]
Hi @KietTruongSFDO. Should this be noted as a "future release" change?

**Comment by KietTruongSFDO** [comment]
@lianeyee This is already fixed and in the code now.

**Comment by lianeyee** [comment]
@KietTruongSFDO Sorry, I wasn't clear. I mean it looks like this change was for Payment Allocations. We've been release noting items for those features with language like "This feature/change is intended for use in a future release and should have no visible impact on your org." Should that be included in this release note?

**Pull request merged**
