### PR TITLE
BGE: Update payments soql string for Review Donations modal

### LINKED ISSUE #4272: BGE Grid - Unpaid payments from Closed Opportunities showing on review donations modal
Unpaid payments belonging to Closed Opportunities are currently being incorrectly shown in the Review Donations modal from the BGE grid.
Review donations modal should display only the following:
 
For Payments:
Unpaid Payments from open opportunities with multiple unpaid payments
Unpaid Payments from open opportunities with both paid and unpaid payments
Unpaid Payments from open opportunities with a single unpaid payment
 
For Opportunities:
Opportunities in any open stage with no payments
Opportunities in any open stage with multiple paid payments
 

Preconditions:
Having a closed opportunity with an unpaid payment
Being in BGE grid
 
Steps to reproduce:
Go to BGE and open access any batch
Use the lookup field to look for the Contact/Account for the closed opportunity
Click on Review Donations
 
Expected results:
A spinner will briefly load but no Review Donations link will be shown since there are no valid Payments or Opportunities to be shown in the modal.
 
Actual results:
Review Donations link appears and the modal displays the Payments belonging to a closed opportunity.

### PR DESCRIPTION
**Pull request by psadie**
Prior to this change, unpaid payments that looked up to a closed opportunity and written off payments were being included in the 'Review Donations' modal query. This change updates the query to exclude , unpaid payments that look up to a closed opportunity and payments that have been written off.

# Critical Changes

# Changes
- In Batch Gift Entry, when you click the Review Donations button to review possible matching donations, you'll no longer see unpaid Payments related to closed Opportunities. If there are matching open Opportunities with unpaid Payments, you'll see those unpaid Payments.

# Issues Closed
- Fixes #4272 

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by psadie** [comment]
lurch: attach W-031021

**Comment by psadie** [comment]
lurch: attach W-031021

**Comment by psadie** [comment]
**lurch: attach W-031021

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fR8RQAU" target="_blank">W-031021</a>

**Pull request merged**
