### PR TITLE
Unify BDI QA data with regular QA data (new)

### PR DESCRIPTION
**Pull request by prescod**
Replaces WorkOrder with CustomOrder 2.

Supercedes  #4587

### CODE REVIEW

**Comment by prescod** [comment]
@davidmreed : David Glick says that the failing tests here are Chrome 77 and should not block merging.

**Comment by prescod** [comment]
@skristem @deepmalamehta

Can one of you check this branch out and validate whether I've broken your tests?

**Comment by skristem** [comment]
my current bdi tests still work fine. Thanks for checking

**Comment by davidmreed** [comment]
Approving based on confirmation that BDI tests are good to go.

**Pull request merged**
