### PR TITLE
Update Account Conversion page to use SLDS

### PR DESCRIPTION
**Pull request by dospromptman**
# Warning

# Info
The Account Conversion page has been updated to use Salesforce Lightning Design System look and feel.  This includes an updated component for showing Apex job progress and page messages using SLDS.

# Issues

### CODE REVIEW

**Comment by dospromptman** [comment]
@chrismcmahon this is a UI heavy update. Do you want to look at it while it is in code review, or do you prefer your QA start after merge?

**Comment by chrismcmahon** [comment]
Go ahead and merge, that's a little easier for me to manage the test org.

**Comment by dospromptman** [comment]
I brought the "boxy" layout of the page over from the existing version, but I'm thinking it might look better if I dropped the boxes.  The SLDS page on layout does suggest that full width header is better... https://www.lightningdesignsystem.com/design/layout

**Comment by dospromptman** [comment]
I'm going to repackage this as separate pull requests.  Closing this one.

**Pull request closed without merging**
