### PR TITLE
Fixing null string exception.

### PR DESCRIPTION
**Pull request by njjc**
# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by lmeerkatz** [comment]
@njjc Can you attach this to its work item? (**lurch:attach W-0000000)

**Comment by lmeerkatz** [comment]
**lurch:attach W-029124

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007fOhUAAU" target="_blank">W-029124</a>

**Comment by lmeerkatz** [comment]
@njjc It looks like there's a test failure. It looks like a row lock problem to me. Do you agree? If so, do you resolve those with manual rebuilds or do you update tests to stabilize them? https://mrbelvedereci.herokuapp.com/builds/39595/tests

**Comment by njjc** [comment]
@lmeerkatz that's strange, I've never seen a row lock in apex tests before. Generally when there are one time intermittent failures we will just rerun, and if they happen often enough we add a backlog item to fix it.

**Comment by force2b** [comment]
@njjc I have seen that on occasion. It's part of the data rollback process, and effectively the main reason we have issues with moving to parallel unit tests. What _should_ happen is that each test method has its own set of data isolated from all other unit tests, but what _actually_ happens is that the data is isolated, but the object index is shared. 

I've been told that when one test is trying to rollback data and the index is being updated, it can cause a lock error in another unit test that may be updating the index with the same key value. That's the primary reason why I've ben pushing to use unique Name values in all of our unit tests. Of course, even with unique values I've still seen some occasional lock errors against objects such as OpportunityContactRole that shouldn't be subject to this problem.

**Comment by davisagli** [comment]
@njjc @lmeerkatz heads-up that since this was merged, there is a failing test in the beta builds: BDI_DataImport_TEST.OneDIWithoutFirstName

Stack Trace:
Class.npsp.BDI_DataImport_TEST.OneDIWithoutFirstName: line 160, column 1

Message:
System.AssertException: Assertion Failed: Expected: 1, Actual: 2

**Comment by njjc** [comment]
Thanks @davisagli I'll check it out.

**Pull request merged**
