### PR TITLE
Feature/robot  prerelease19 fix

### PR DESCRIPTION
**Pull request by skristem**
# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by davidmreed** [comment]
@skristem, looks like two of the 3 failures in Feature-Robot Prerelease have to do with the link to the created Contact not being followed and the browser being still at Object Home. The third I'm not sure about.

I restarted the build with failed Apex tests, which aren't meaningful failures for this feature.

**Comment by davidmreed** [comment]
@skristem I think I remember that you decided to rebuild these changes in a new branch. Should this PR be closed/deleted?

**Comment by skristem** [comment]
Hi David, yes I have created a new branch and working on it. I am not sure what is our process for removing this

**Comment by davisagli** [comment]
@skristem @davidmreed I'll go ahead and remove this one.

**Pull request closed without merging**
