### PR TITLE
Implementing Schedulable interface for Opp Naming Batch.

### LINKED ISSUE #2455: Recurring Donation Batch Error "List index out of bounds: 1"
Create Household Contact
Add Recurring Donation (open)
Delete Contact (with override button)

Result:
In my org, I received 2 identical emails:

Errors:

Error #1:

Error Type: Other
Error Date: 2016-12-21 12:59:22
Message: "entity is deleted"
https://npsp.na35.visual.force.com/a0941000001mbvyAAA

Stack Trace:
null

Error #2:

Error Type: System.ListException
Error Date: 2016-12-21 12:59:22
Message: "List index out of bounds: 1"

Stack Trace:
Stacktrace available at the time of saving the record - (npsp)

### PR DESCRIPTION
**Pull request by njjc**
# Critical Changes

# Changes
- Opportunity Naming batch job can now be scheduled.
- Removed cascade deletion of Recurring Donations and Allocations until some issues with contact merge are sorted out.

# Issues Closed
- Fixes #2455

### CODE REVIEW

**Comment by njjc** [comment]
@davidhabib This pull request fixes the recurring donations rollup issue, removes all cascade deletion functionality, and makes the opportunity naming batch class schedulable.

**Comment by davidhabib** [comment]
@njjc can you add the nightly rd error to the list of issues closed.  thanks.

**Comment by njjc** [comment]
@davidhabib thanks for the fixes, I had to create a new issue for the error fixed, #2455, to differentiate it from #2377.

**Comment by judisohn** [comment]
@njjc This fixes #2435, correct? That's still sitting as open.

**Comment by njjc** [comment]
Yep, I'll close it. I think not including the issue in the release is fine because I wrote out the change in Changes.

**Comment by judisohn** [comment]
That's fine, I was just cleaning up the Milestones for the new sprint and noticed it was still open. Thanks!

**Pull request merged**
