### PR TITLE
Prevent XSS on Relationship Viewer

### LINKED ISSUE #3843: Relationship Viewer Labels XSS Vulnerability
To prevent XSS, the Custom Labels on the Relationship Viewer should be properly escaped.

### PR DESCRIPTION
**Pull request by jjbennett**
// The SFDX VSCODE plugin auto format fixed a bunch of spacing issues it detected, if that makes this PR to noisy please let me know and I will turn that off. The actual change here is using JSINHTMLENCODE on the labels used in jQuery.

# Critical Changes
- Security Issues addressed on the NPSP Relationship Viewer Page.

# Changes

# Issues Closed
- Fixes #3843 

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007fMMyAAM" target="_blank">W-027002</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AXlRtAAL" target="_blank">W-025132</a>

**Comment by jjbennett** [comment]
@rponti-sforg - this is ready for testing but ok not to qa this sprint, picked this item up. Thanks!

**Comment by jjbennett** [comment]
@rponti-sforg - This one is marked fixed in AA, does this still need QA?

**Comment by rponti-sforg** [comment]
@jjbennett I am finished testing this.  All Custom Labels associated with Relationship Viewer are properly escaped and do not throw XSS pop-up when trying to view Relationship Viewer when using Spanish.  

Before I can merge, the PR has conflicts that need to be resolved.  Can you take a peek at that?

**Pull request merged**
