### PR TITLE
Prevent XSS on Opportunity Acknowledgement Page and fix Account Model Health Text

### PR DESCRIPTION
**Pull request by jjbennett**
# Critical Changes

# Changes
- Security Issues addressed on Opportunity Acknowledgement page.

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by jjbennett** [comment]
**lurch: attach W-030672

**Comment by jjbennett** [comment]
**lurch: attach W-030040

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fQg3QAE" target="_blank">W-030672</a>

**Comment by jjbennett** [comment]
@rponti-sforg - this item is ready for testing. Note: 2 work items are attached to this PR. The one was a bug fix from the Settings XSS PR where an error was displaying the html tags instead of the line breaks. This Health Check failure and be created by creating sample data in a scratch org then going into the settings and changing the Household model to one.
To see the error on the Opp Send Acknowledgement page, you can go into a donation record and click the Send Acknowledgement button. Since we do not activate the workflow rule by default the message should display.
Thanks!

**Comment by jjbennett** [comment]
@rponti-sforg - Fixed the strong tag, nice catch!

**Comment by sam-knox** [comment]
@jjbennett - Is there a related Issue for this PR?

**Comment by jjbennett** [comment]
No in quip there was a discussion about just added the change comment and not really needing to create a matching issue for it.

**Pull request merged**
