### PR TITLE
CCI: Activate "Pledged" Stage in Deploy_Dev_Config task

### PR DESCRIPTION
**Pull request by force2b**
Update the CCI `deploy_dev_config` task to activate the "Pledged" Stage. Otherwise it gets added as Inactive.

# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by davisagli** [comment]
Should this get added to `deploy_dev_config_managed` (that is, in the `src_managed` directory) too for when CCI installs Cumulus as a managed package)?

**Comment by force2b** [comment]
Good point @davisagli. I'll add that.

**Comment by davisagli** [comment]
@force2b yeah, I thought that's what I was communicating by clicking "approve". Is there a convention of Cumulus PRs getting merged by someone other than the person who opened them?

**Comment by force2b** [comment]
No worries. Generally the person who approves merges (or QA merges for those stories going through QA). CCI type PR's a bit different though. I'll merge this.

**Pull request merged**
