### PR TITLE
When converting a lead, I may want the opportunity created to be related to a contact's primary affiliation

### LINKED ISSUE #1846: When converting a lead, I may want the opportunity created to be related to a contact's primary affiliation
**External Contribution Issue created by @cdcarter**

As a user converting leads, I want the option to create the opportunity on the lead's new primary affiliation instead of on their household, so that I can use leads to track corporate gifts/sponsorships.

On the NPSP lead convert override, we have the option to create a primary affiliation for a contact to the Lead's "Company". A checkbox to also associate the opportunity with that Organization account (though maintaining the OCR) would allow organizations that use Leads to track corporate sponsorship to not have to manually update created opportunities.

### PR DESCRIPTION
**Pull request by mrbelvedere**
Has been tested by Beth Breisnes, Beth Howard, and Ryan Ozimek. I made the decision to use static labels for account name selection instead of trying to populate actual account names just to get the feature done, but I may spend some time filling those in later. 

# Contribution Info

This external contribution was submitted by @cdcarter and Fixes #1846

# Critical Changes

#1839 - When a Lead converts with an Opportunity, set the Opp Primary Contact field.
#1846 - Provide an option for converting a lead with an Opportunity to the Lead Company instead of the Individual/HH/Bucket acct.

# Changes

# Issues

Fixes #1846

### CODE REVIEW

**Comment by cdcarter** [comment]
Ryan Ozimek adds question: "I think some number of folks might not want to fill out the Opportunity.PrimaryContact field due to downstream effects. I believe that Nic has said that if you don’t fill out that field when creating the Opportunity, none of those downstream effects happens.  Do you know if this new Lead conversion process could allow the user to choose whether or not to fill out that field?"

Certainly easy to add another option to lead conversion, but I don't know enough about the Primary Contact field to determine what core behavior should be here.

**Comment by judisohn** [comment]
My $0.02 if I'm understanding this correctly: If there is an Opportunity Contact Record marked as Primary, that contact should be the Opportunity.Primary Contact. I don't think it's a good idea to have the Primary OCR record while not populating Opportunity.Primary Contact.

**Comment by cdcarter** [comment]
My understanding is that of yours, @judisohn. @njjc -- is there a reason there should ever be a Primary OCR without `Opportunity.Primary_Contact__c` set?

**Comment by judisohn** [comment]
Hi @cdcarter - just a heads up that @njjc is out this week. Given that and other priorities, we don't have it in our current sprint to review this. But hang tight and we should get to it soon! Thanks!

**Comment by cdcarter** [comment]
UNACCEPTABLE! :) No rush at all, whenever it fits into your release cycle is appropriate. That might even give me some time to pretty up the `vfp`.

**Comment by cdcarter** [comment]
Just spoke with @judisohn, and both #1801 and #1571 are both pretty relevant here, so I'm going to try and tackle them in this PR too, starting with #1801.

**Comment by cdcarter** [comment]
Instead of continuing to fiddle with this and cause frustration on any end, I'm calling the things I wanted to accomplish in this PR *done* and in your hands @judisohn + team to review and do what you will with. Here's the final count of everything happening here, along with a quick summary of discussion around it:

* Add one choice on the Lead Convert page to choose what account the converted Opportunity is associated with (the contact's primary account, or their new affiliation)
* When an Opportunity is created, it's `Primary_Contact__c` is set to the converted Contact. There was some concern about users who may not want the behavior of `Primary_Contact__c` and a suggestion of adding an additional choice. Instead of doing that, this contributor suggests that orgs that do not like the behavior of Primary_Contact__c should instead disable related triggers instead of using inconsistent data.
* Add a set of CompanyAddress fields to Lead
* When converting a Lead and creating a new affiliated Company account, set it's BillingAddress to the CompanyAddress values.
* When converting a Lead and creating a new Company account as the main account, set it's BillingAddress to CompanyAddress if populated (behavior as described by @davidhabib in comments on #1801).

I'm stopping work here. Go forth and review, and decide whether or not merging any/some/all is a good idea.

**Comment by davidhabib** [comment]
Thanks for your work on this Christian.  We will look at it and try to get it integrated in our next sprint, which starts mid December.

**Comment by cdcarter** [comment]
+1

**Comment by njjc** [comment]
Moved over to #1888

**Pull request closed without merging**
