### PR TITLE
Update to Manage Allocations page to show correct total with negative payments

### LINKED ISSUE #3816: Payment Allocations: With refunds, the Manage Allocations page is not showing the correct amounts, or totaling refund allocations correctly
User type (As a...) Goal (I want to...) Reason (so that...) Additional Details
The Payment allocations related list is showing correctly but the Manage Allocations page is not showing the negative/refund allocation totals correctly.

Steps to reproduce:
Setup: Payment allocations enabled and a default gau choosen. I created an opportunity of $100 and left the oppt allocation at 100% for the default gau. I also had a payment that was paid for $100 already.
1. Create another payment of -20 and paid with today's date. The payment allocation by default was (20) for default gau.
2. I went to manage allocations page and I couldn't quite allocate the amount correctly (because of this issue), so instead I clicked the new button on the payment allocations related list and did a -5 allocation to a misc gau. It shows up correctly as (15) default gau and (5) as misc gau. 
3. Go to the manage allocations page. It shows -5 for each, that is not correct. 
4. If I try to change misc as -15 on this page it matches the default fund and shows -15 for it as well (even though the payment is only -20 total.

We need to update the VF page to show the correct default GAU amount.

We need to make sure that the manage allocations page still works well for positive allocation amounts as well.

### PR DESCRIPTION
**Pull request by lparrott**
# Critical Changes

# Changes

- Update to the Manage Allocations page to show the correct total for negative payments.

# Issues Closed

Fixes #3816

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by lparrott** [comment]
@randi274 @bethbrains We made a small Javascript change to the Manage Allocations page to allow it to work with negative payments, not sure if either of you wanted to take a look? Still getting used to the review cycle with NPSP changes...

We'll also be doing our own code review and QA. Thanks!

**Comment by randi274** [comment]
@lparrott I might defer to @force2b or @jjbennett to review this, as they've worked with this page and are much more familiar with the code for Allocations than myself or @bethbrains. Thanks!

**Comment by force2b** [comment]
@lparrott Is this associated with a WI in AA (or a GH issue) that has steps to reproduce the original issue being fixed?

**Comment by lparrott** [comment]
@force2b Yes, I just created an issue and attached the WI. @annejackson will be doing QA, I just wanted to make your team aware of the change. It only became an issue now that we allow negative payments (refunds) to have allocations, which messed up the calculations on this page.

**Comment by lparrott** [comment]
**lurch: attach W-029630

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fPNBQA2" target="_blank">W-029630</a>

**Comment by annejackson** [comment]
Looks good. Merging!

**Comment by annejackson** [comment]
Will delete branch as well. Thanks @lparrott

**Pull request merged**
