### PR TITLE
filtering out contacts after querying instead of using "NOT IN" to av…

### LINKED ISSUE #3978: Search bar in Manage Household button is not working
Issue on:
Household(account) I have a button called 'Manage Household' and it has a search bar to search Contacts, which is not working.

NPSP version :
Nonprofit Success Pack | Salesforce.org | 3.144

Error statement:
getting an error in the log which is 
"This page has an error. You might just need to refresh it. Error in $A.getCallback() [] Callback failed: apex://npsp.HH_AutoCompleteDataProvider_LCTRL/ACTION$queryObjects Failing descriptor: {npsp:autocomplete}"

Snapshot:
image

Looking forward to hear as soon as possible.

cheers,
Preeti Agarwal

### PR DESCRIPTION
**Pull request by seanpat09**
…oid SOQL bug

# Critical Changes

# Changes

# Issues Closed
Fixes #3978

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by seanpat09** [comment]
**lurch: attach W-030566

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fQXVQA2" target="_blank">W-030566</a>

**Comment by seanpat09** [comment]
@force2b Should I merge this to master now that you've successfully tested this in a Spring '19 or or should we also have @rponti-sforg do QA on this work item?

**Comment by force2b** [comment]
We should have @rponti-sforg QA as well, just to be thorough.

**Pull request merged**
