### PR TITLE
Updated TDTM_ObjectDataGateway class method to fix null pointer error in case trigger action is null.

### LINKED ISSUE #2742: Trigger Handler Null Pointer Exception when the Trigger Action is empty
The trigger action field is not required and can be nulled out by an end user. This will result in an error message for both Health Check and when the trigger is ran on the object: "System.NullPointerException: Attempt to de-reference a null object Class.TDTM_ObjectDataGateway.getClassesToCallForObject: line 74, column 1 External entry point Class.TDTM_TriggerHandler.run: line 89, column 1 Trigger.TDTM_Account: line 34, column 1"

### PR DESCRIPTION
**Pull request by manikrai29**
Updated TDTM_ObjectDataGateway class method (getClassesToCallForObject()) to fix null pointer error in case trigger action is null.

# Critical Changes

# Changes
Added and extra check (th.Trigger_Action__c != null) to make sure Trigger Action is not null and in case it is null we never call that particular class (as user never specified when to call it).

# Issues Closed
#2742

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by coriobriensfdo** [comment]
**lurch: attach W-020423

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008F6wYAAS" target="_blank">W-020423</a>

**Comment by coriobriensfdo** [comment]
Thanks @manikrai29! As soon as we get the signed CLA back we can move forward on this :)

**Comment by RadSFDeveloper** [comment]
Thank you @manikrai29 for your contribution. This PR will be closed since we have pulled changes into new PR #4564 so it could go through process of review and QA.

**Pull request closed without merging**
