### PR TITLE
Enabling Customizable Rollups the first time does not fully enable the feature

### LINKED ISSUE #4346: Enabling Customizable Rollups the first time does not fully enable the feature
When you Enable CRLP for the first time, the “Deployment in progress” page never seems to refresh despite the deployment completing. You need to refresh that page and enable CRLP again in order to see that they are enabled.

## Steps to reproduce

* Open *NPSP Settings > Donations > Customizable Rollups* and enable CRLP
* Page should load and display “Deployment in progress. You can leave this page. This page will reload when deployment is finished”
* In another tab/window, open the *Deployment Status *page* *again and make sure the deployment has completed (you can tell because it should have a different timestamp from all the other deployments from the initial push to the scratch org)
* The page in NPSP Settings still has not reloaded.
* In another tab/window, open up *Setup > Custom Settings > Customizable Rollup Settings > Manage*. You should see that “*Enable Customizable Rollups*” is still unchecked.
* Go back to NPSP Settings. Refresh the page and go to* Donations > Customizable Rollups* and enable CRLP again.
* Page will eventually refresh and show that CRLP has been enabled.
* If you go to the custom settings again, you will also see that “*Enable Customizable Rollups*” is now checked

Thanks to @seanpat09 for documenting.

### PR DESCRIPTION
**Pull request by RadSFDeveloper**
# Critical Changes

# Changes
In addition to resolving an issue with Customizable Rollups not being enabled on the first try, we also resolved an issue where customers received a false timeout error message every time they saved a new or updated Customizable Rollup or Filter Group. Note that this does not completely resolve intermittent false timeouts that we have been tracking and we are still investigating a different strategy. If you do receive a false timeout, go to Setup --> Deployment Status and verify that the deployment succeeded. Otherwise, you may be at risk of duplicate records.

# Issues Closed
Fixes #4346 

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by RadSFDeveloper** [comment]
**lurch: attach W-034034

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C6maQAC" target="_blank">W-034034</a>

**Comment by RadSFDeveloper** [comment]
**lurch: attach W-033047

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087ugdQAA" target="_blank">W-033047</a>

**Comment by RadSFDeveloper** [comment]
@rponti-sforg , I've just updated PR to track W-033047 and set issue #4231  as fixed in addition to the Customizable Rollup enable issue. Can you please test Rollup create and update as well based on the #4231 ?

**Comment by RadSFDeveloper** [comment]
**lurch: dettach W-033047

**Comment by RadSFDeveloper** [comment]
**lurch: detach W-033047

**Comment by LurchTheButler** [comment]
Detached <a href="https://foundation.my.salesforce.com/a2x1E000001C6maQAC" target="_blank">W-034034</a>

**Comment by rponti-sforg** [comment]
QE testing is complete.  Tests have passed.

For further testing details, see: https://foundation.lightning.force.com/lightning/r/agf__ADM_Work__c/a2x1E000001C6maQAC/view

Merging PR and deleting branch.

**Pull request merged**
