### PR TITLE
CCI: Add new testing rollups to the CRLP Testing Flow

### PR DESCRIPTION
**Pull request by force2b**
Adds a whole series of InKind and other rollup definitions (created by @jesslopez-sf) to the `deploy_rollup_testing` CCI Flow to aid in Customizable Rollups testing.

To use:
* Create a Scratch Org
* Enable Customizable Rollups
* `cci flow run deploy_rollup_testing --org {orgname}
* Open the scratch org and confirm that all of the new Rollup Definitions and Filter Groups are in the org
* Create any necessary test data specific to the new rollups
* Run the rollups batches
* Add fields to the layouts to review

# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by force2b** [comment]
@jesslopez-sf Thanks. Executing the class is up to you. I think I posted a video in chatter somewhere, but at the moment the class isn't validating any of these new rollup types added in this PR. That's a goal, but haven't had time to do that yet.

Out of curiosity, do you think it would be helpful to include updated Account and Contact page layouts with all the new fields in this cci task?

**Comment by judisohn** [comment]
@force2b @jesslopez-sf I love it. How about adding the fields in a 'Testing Fields' section so it's 1 easier to find/evaluate and 2 clear that this is special for this process and not what customers would otherwise get in their layouts?

**Comment by force2b** [comment]
@jesslopez-sf Feel free to merge this once you're happy with the layouts I added to the flow. Thanks for reviewing.

**Comment by jesslopez-sf** [comment]
Looks good, @force2b. Merging now.

**Pull request merged**
