### PR TITLE
Feature/1329 multicurrency setscale

### LINKED ISSUE #1329: As a user, multicurrency orgs should not improperly round currency conversion so that my converted values are accurately portrayed when aggregated to Contacts or Households
I think its here: 
https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/RLLP_OppRollup_UTIL.cls#L305

Original thread: 
https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D58000001grohV&fromEmail=1

### LINKED ISSUE #1345: BUG: As a multicurrency enabled user, Best Gift Year Total field should correctly convert currencies.

### PR DESCRIPTION
**Pull request by njjc**
# Warning
# Info
# Issues
Fixes #1345 
Fixes #1329

### CODE REVIEW

**Comment by njjc** [comment]
@davidhabib @ceiroa Ready for merge.

**Comment by davidhabib** [comment]
@njjc I've reviewed and would accept the request, but it isn't passing build.

**Comment by njjc** [comment]
Very strange, the same build that shows as failing now showed as passing when I commented.

**Comment by njjc** [comment]
@jlantz any idea why the green checkbox should show and then turn into a red X?

[Proof!](https://cloud.githubusercontent.com/assets/1018198/6068560/b27901c0-ad42-11e4-8c3d-7ebd857aa437.png)

**Comment by ceiroa** [comment]
I also looked at the pull request at saw the red x. At that time it was pointing to a failing build: http://ci.salesforcefoundation.org/view/feature/job/Cumulus_feature/3348/console

**Comment by njjc** [comment]
Yep, I saw that too, but it showed the same build as failing that I had seen as passing when I originally posted my @mention comments.

**Pull request merged**
